package org.dockbox.hartshorn.palswap.init;

import org.dockbox.hartshorn.palswap.init.VanillaProps.ModGroups;
import org.dockbox.hartshorn.palswap.init.VanillaProps.RenderLayer;
import org.dockbox.hartshorn.palswap.init.VanillaProps.TypeList;

public class LeavesInit {

    public static void init() {
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("beech_tree_leaves")
                .manual()
                .foliageColor()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("bright_autumnal_beech_tree_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("faded_autumnal_beech_tree_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("autumnal_beech_tree_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("ash_tree_leaves")
                .manual()
                .foliageColor()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("dead_deciduous_branches")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("dead_pine_needles")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("dead_spruce_needles")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("light_spruce_needles")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("dark_spruce_needles")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("pine_needles")
                .manual()
                .foliageColor()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("autumnal_oak_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("autumnal_birch_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("autumnal_maple_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("autumnal_horse_chestnut_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("diseased_horse_chestnut_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("aspen_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("autumnal_aspen_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("rowan_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("mistletoe_garland")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("gorse_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("weeping_willow_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("autumnal_weeping_willow_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("bright_autumnal_weeping_willow_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("yellow_autumnal_weeping_willow_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("downy_willow_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.plants()
                .group(ModGroups.LEAVES)
                .name("downy_willow_leaves_tip")
                .manual()
                .family("downy_willow_leaves")
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("horse_chestnut_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("goat_willow_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("larch_needles")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("yellow_autumnal_larch_needles")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("orange_autumnal_larch_needles")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("lilac")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("pink_cherry_blossoms")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("white_cherry_blossoms")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("red_cherry_blossoms")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("purple_cherry_blossoms")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("dark_beech_tree_leaves")
                .manual()
                .foliageColor()
                                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("apple_tree_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("cherry_tree_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("holly_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("orange_tree_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("pear_tree_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("plum_tree_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("grape_vine_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("lemon_tree_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leaves()
                .group(ModGroups.LEAVES)
                .name("olive_tree_leaves")
                .manual()
                                .randomTick(true)
                .register(TypeList.of(Void.class));
        VanillaProps.leafLike()
                .group(ModGroups.LEAVES)
                .render(RenderLayer.CUTOUT_MIPPED)
                .name("caribbean_royal_palm_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leafLike()
                .group(ModGroups.LEAVES)
                .render(RenderLayer.CUTOUT_MIPPED)
                .name("caribbean_royal_palm_leaves_corner")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leafLike()
                .group(ModGroups.LEAVES)
                .render(RenderLayer.CUTOUT_MIPPED)
                .name("old_caribbean_royal_palm_leaves")
                .manual()
                                .register(TypeList.of(Void.class));
        VanillaProps.leafLike()
                .group(ModGroups.LEAVES)
                .render(RenderLayer.CUTOUT_MIPPED)
                .name("old_caribbean_royal_palm_leaves_corner")
                .manual()
                                .register(TypeList.of(Void.class));
    }
}
