package org.dockbox.hartshorn.palswap.init;

import org.dockbox.hartshorn.palswap.init.VanillaProps.ModGroups;
import org.dockbox.hartshorn.palswap.init.VanillaProps.TypeList;

public class LightsInit {

    private static final int[] lightValues = { 5, 10, 14 };

    public static void init() {
        VanillaProps.stone()
                .group(ModGroups.LIGHTING)
                .name("campfire")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("torch_with_grille")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("victorian_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("hanging_oil_lamp")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("hanging_candle_holder")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("elven_hand_light")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("candle")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("big_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("candelabra")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("candles")
                .manual()
                .blocking(false)
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("chandelier")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("cross_chandelier")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("hand_candle")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("hanging_brazier")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("candle_in_a_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("ship_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("small_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.plantLike()
                .group(ModGroups.LIGHTING)
                .name("white_paper_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.plantLike()
                .group(ModGroups.LIGHTING)
                .name("yellow_paper_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.plantLike()
                .group(ModGroups.LIGHTING)
                .name("small_red_paper_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("brazier")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("oil_lamp")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("chinese_palace_lantern")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("iron_candelabrum_1")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .name("iron_candelabrum_2")
                .family("iron_candelabrum_1")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .name("iron_candelabrum_3")
                .family("iron_candelabrum_1")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("golden_candelabrum_1")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .name("golden_candelabrum_2")
                .family("golden_candelabrum_1")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .name("golden_candelabrum_3")
                .family("golden_candelabrum_1")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.metal()
                .group(ModGroups.LIGHTING)
                .name("terracotta_oil_lamp")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .name("invisible_light_low")
                .family("invisible_light")
                .blocking(false)
                .texture("block/5_miscellaneous/invisible")
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .name("invisible_light_medium")
                .family("invisible_light")
                .blocking(false)
                .texture("block/5_miscellaneous/invisible")
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.UTILITY)
                .name("invisible_light")
                .blocking(false)
                .texture("block/5_miscellaneous/invisible")
                .register(TypeList.of(Void.class));
    }

}
