package org.dockbox.hartshorn.palswap.init;

import org.dockbox.hartshorn.palswap.init.VanillaProps.ModGroups;
import org.dockbox.hartshorn.palswap.init.VanillaProps.TypeList;

public class PlasterInit {

    public static void init() {
        TypeList types = null, typesVanilla = null;
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("rough_white_plaster")
                .texture("block/2_advanced_refined/3_plaster/rough_white_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("blue_painted_wall")
                .texture("minecraft:block/blue_concrete")
                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("green_painted_wall")
                .texture("minecraft:block/lime_concrete")
                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_painted_wall")
                .texture("minecraft:block/red_concrete")
                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_brown_plaster")
                .texture("block/2_advanced_refined/3_plaster/worn_brown_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("rose_plaster")
                .texture("block/2_advanced_refined/3_plaster/rose_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("roman_brick_with_rose_plaster")
                .texture("block/2_advanced_refined/3_plaster/roman_brick_with_rose_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("peach_plaster")
                .texture("block/2_advanced_refined/3_plaster/peach_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_peach_plaster")
                .texture("block/2_advanced_refined/3_plaster/worn_peach_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_yellow_plaster_on_brick")
                .texture("block/2_advanced_refined/3_plaster/worn_yellow_plaster_on_brick")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("yellow_plaster")
                .texture("block/2_advanced_refined/3_plaster/yellow_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_yellow_plaster")
                .texture("block/2_advanced_refined/3_plaster/worn_yellow_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_magenta_plaster")
                .texture("minecraft:block/magenta_terracotta")
                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("magenta_plaster")
                .texture("block/2_advanced_refined/3_plaster/magenta_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_light_gray_plaster")
                .texture("minecraft:block/light_gray_terracotta")
                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("light_gray_plaster")
                .texture("block/2_advanced_refined/3_plaster/light_gray_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_white_plaster")
                .texture("block/2_advanced_refined/3_plaster/worn_white_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_plaster")
                .texture("block/2_advanced_refined/3_plaster/white_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_white_plaster_with_red_masonry_lines")
                .texture("block/2_advanced_refined/3_plaster/worn_white_plaster_with_red_masonry_lines")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_plaster_with_red_masonry_lines")
                .texture("block/2_advanced_refined/3_plaster/white_plaster_with_red_masonry_lines")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_plaster_with_masonry_lines")
                .texture("block/2_advanced_refined/3_plaster/white_plaster_with_masonry_lines")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("worn_purple_plaster")
                .texture("minecraft:block/purple_terracotta")
                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("purple_plaster")
                .texture("block/2_advanced_refined/3_plaster/purple_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("light_blue_plaster")
                .texture("block/2_advanced_refined/3_plaster/light_blue_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_stucco")
                .texture("block/2_advanced_refined/3_plaster/white_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("tan_stucco")
                .texture("block/2_advanced_refined/3_plaster/tan_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("clay_mud_wall")
                .texture("block/2_advanced_refined/3_plaster/clay_mud_wall")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("purple_stucco")
                .texture("block/2_advanced_refined/3_plaster/purple_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("magenta_stucco")
                .texture("block/2_advanced_refined/3_plaster/magenta_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_stucco")
                .texture("block/2_advanced_refined/3_plaster/red_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("light_red_stucco")
                .texture("block/2_advanced_refined/3_plaster/light_red_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("orange_stucco")
                .texture("block/2_advanced_refined/3_plaster/orange_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("orange_plaster")
                .texture("block/2_advanced_refined/3_plaster/orange_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("lime_stucco")
                .texture("block/2_advanced_refined/3_plaster/lime_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("green_stucco")
                .texture("block/2_advanced_refined/3_plaster/green_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("cyan_stucco")
                .texture("block/2_advanced_refined/3_plaster/cyan_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("light_blue_stucco")
                .texture("block/2_advanced_refined/3_plaster/light_blue_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("blue_stucco")
                .texture("block/2_advanced_refined/3_plaster/blue_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("black_stucco")
                .texture("block/2_advanced_refined/3_plaster/black_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("light_sienna_stucco")
                .texture("block/2_advanced_refined/3_plaster/light_sienna_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("burnt_sienna_stucco")
                .texture("block/2_advanced_refined/3_plaster/burnt_sienna_stucco")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("brown_plaster")
                .texture("block/2_advanced_refined/3_plaster/brown_plaster")
                .register(types);
    }
}
