package org.dockbox.hartshorn.palswap.init;

import org.dockbox.hartshorn.palswap.init.VanillaProps.ModGroups;
import org.dockbox.hartshorn.palswap.init.VanillaProps.TypeList;

public class WallDesignsNoWallInit {

    public static void init() {
        TypeList types= null;
        TypeList typesOverlay= null;
        TypeList typesOverlayPillar= null;
        VanillaProps.stone()
                .group(ModGroups.ADVANCED_MASONRY_AND_CERAMICS)
                .name("chiseled_polished_parian_marble_design")
                .texture("top", "minecraft:block/chiseled_quartz_block_top")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "minecraft:block/chiseled_quartz_block")
                                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("orange_plaster_with_sandstone_base")
                .texture("top", "block/2_advanced_refined/3_plaster/orange_plaster")
                .texture("bottom", "minecraft:block/sandstone_bottom")
                .texture("*", "block/2_advanced_refined/3_plaster/orange_plaster_with_sandstone_base")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_spiral_wall_design")
                .texture("block/2_advanced_refined/3_plaster/red_spiral_wall_design")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("wallpaper_with_gilded_border")
                .texture("block/2_advanced_refined/3_plaster/wallpaper_with_gilded_border")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.ADVANCED_MASONRY_AND_CERAMICS)
                .name("fancy_blue_marble_design")
                .texture("block/2_advanced_refined/1_stone/3_marble/fancy_blue_marble_design")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("wallpaper_with_fleur_de_lis")
                .texture("block/2_advanced_refined/3_plaster/wallpaper_with_fleur_de_lis")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("blue_baroque_wallpaper")
                .texture("block/2_advanced_refined/3_plaster/blue_baroque_wallpaper")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_baroque_wallpaper")
                .texture("block/2_advanced_refined/3_plaster/red_baroque_wallpaper")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("yellow_baroque_wallpaper")
                .texture("block/2_advanced_refined/3_plaster/yellow_baroque_wallpaper")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("blue_wallpaper")
                .texture("block/2_advanced_refined/3_plaster/blue_wallpaper")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("green_wallpaper")
                .texture("block/2_advanced_refined/3_plaster/green_wallpaper")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_wallpaper")
                .texture("block/2_advanced_refined/3_plaster/red_wallpaper")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("fancy_gray_elven_plaster")
                .texture("top", "block/2_advanced_refined/3_plaster/fancy_gray_elven_plaster_topbottom")
                .texture("bottom", "block/2_advanced_refined/3_plaster/fancy_gray_elven_plaster_topbottom")
                .texture("*", "block/2_advanced_refined/3_plaster/fancy_gray_elven_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_yellow_and_blue_checker_pattern")
                .texture("block/2_advanced_refined/3_plaster/red_yellow_and_blue_checker_pattern")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_baroque_wall")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("bottom", "block/1_basic_refined/1_stone/4_marble/nero_africano_black_marble")
                .texture("*", "block/2_advanced_refined/3_plaster/white_baroque_wall")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("green_baroque_wall")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("bottom", "block/1_basic_refined/1_stone/4_marble/nero_africano_black_marble")
                .texture("*", "block/2_advanced_refined/3_plaster/green_baroque_wall")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("black_baroque_wall")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("bottom", "block/1_basic_refined/1_stone/4_marble/nero_africano_black_marble")
                .texture("*", "block/2_advanced_refined/3_plaster/black_baroque_wall")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("simple_red_socle")
                .texture("bottom", "block/2_advanced_refined/3_plaster/magenta_stucco")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/simple_red_socle")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlayPillar);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("fancy_magenta_socle")
                .texture("bottom", "block/2_advanced_refined/3_plaster/magenta_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/fancy_magenta_socle")
                .texture("*", "block/2_advanced_refined/3_plaster/magenta_stucco")
                .register(typesOverlayPillar);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("fancy_black_socle")
                .texture("bottom", "block/2_advanced_refined/3_plaster/black_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/fancy_black_socle")
                .texture("*", "block/2_advanced_refined/3_plaster/black_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("black_painted_frieze")
                .texture("bottom", "block/2_advanced_refined/3_plaster/black_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/black_stucco")
                .texture("overlay", "block/2_advanced_refined/3_plaster/black_painted_frieze")
                .texture("*", "block/2_advanced_refined/3_plaster/black_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("third_style_black_wall")
                .texture("bottom", "block/2_advanced_refined/3_plaster/black_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/black_stucco")
                .texture("overlay", "block/2_advanced_refined/3_plaster/third_style_black_wall")
                .texture("*", "block/2_advanced_refined/3_plaster/black_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("third_style_red_wall_1")
                .texture("bottom", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("overlay", "block/2_advanced_refined/3_plaster/third_style_red_wall_1")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("third_style_red_wall_2")
                .texture("bottom", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/third_style_red_wall_2")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("third_style_red_wall_3")
                .texture("bottom", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/third_style_red_wall_3")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("black_wall_and_magenta_cornice")
                .texture("bottom", "block/2_advanced_refined/3_plaster/black_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/black_wall_and_magenta_cornice")
                .texture("*", "block/2_advanced_refined/3_plaster/black_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("etruscan_wall_design_1")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/etruscan_wall_design_1")
                .texture("*", "block/2_advanced_refined/3_plaster/white_plaster")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("etruscan_blue_meander_pattern")
                .texture("top", "block/2_advanced_refined/3_plaster/white_plaster")
                .texture("overlay", "block/2_advanced_refined/3_plaster/etruscan_blue_meander_pattern")
                .texture("*", "block/2_advanced_refined/3_plaster/white_plaster")
                .register(typesOverlayPillar);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("fourth_style_white_upper_module_1")
                .texture("top", "block/2_advanced_refined/3_plaster/white_plaster")
                .texture("bottom", "block/2_advanced_refined/3_plaster/white_plaster")
                .texture("*", "block/2_advanced_refined/3_plaster/fourth_style_white_upper_module_1")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("fourth_style_white_upper_module_2")
                .texture("top", "block/2_advanced_refined/3_plaster/white_plaster")
                .texture("bottom", "block/2_advanced_refined/3_plaster/white_plaster")
                .texture("*", "block/2_advanced_refined/3_plaster/fourth_style_white_upper_module_2")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_tooth_pattern_on_white_plaster")
                .texture("top", "block/2_advanced_refined/3_plaster/white_plaster")
                .texture("bottom", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("overlay", "block/2_advanced_refined/3_plaster/red_tooth_pattern_on_white_plaster")
                .texture("*", "block/2_advanced_refined/3_plaster/white_plaster")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_meander_on_red_stucco")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/white_meander_on_red_stucco")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlayPillar);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_plaster_with_red_lines")
                .texture("overlay", "block/2_advanced_refined/3_plaster/white_plaster_with_red_lines")
                .texture("*", "block/2_advanced_refined/3_plaster/white_plaster")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("simple_black_socle")
                .texture("overlay", "block/2_advanced_refined/3_plaster/simple_black_socle")
                .texture("*", "block/2_advanced_refined/3_plaster/black_stucco")
                .register(typesOverlayPillar);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("orange_stucco_with_red_diamond")
                .texture("bottom", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("overlay", "block/2_advanced_refined/3_plaster/orange_stucco_with_red_diamond")
                .texture("*", "block/2_advanced_refined/3_plaster/orange_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_wall_and_black_cornice")
                .texture("bottom", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/red_wall_and_black_cornice")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlayPillar);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_wall_and_fancy_black_cornice")
                .texture("bottom", "block/2_advanced_refined/3_plaster/red_stucco")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay", "block/2_advanced_refined/3_plaster/red_wall_and_fancy_black_cornice")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlayPillar);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_stucco_with_gold_line")
                .texture("overlay", "block/2_advanced_refined/3_plaster/red_stucco_with_gold_line")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlayPillar);
        VanillaProps.planks()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .name("ornate_roman_door_block")
                .texture("block/2_advanced_refined/7_wood/ornate_roman_door_block")
                .register(types);
        VanillaProps.planks()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .family("ornate_roman_door_block")
                .name("ornate_roman_door")
                .register(TypeList.of(Void.class));
        VanillaProps.planks()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .family("ornate_roman_door_block")
                .name("tall_ornate_roman_door")
                .register(TypeList.of(Void.class));
        VanillaProps.planks()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .name("spruce_wood_panel")
                .texture("top", "minecraft:block/spruce_planks")
                .texture("bottom", "minecraft:block/spruce_planks")
                .texture("*", "block/2_advanced_refined/7_wood/spruce_wood_panel")
                .register(types);
        VanillaProps.planks()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .name("fancy_birch_wood_panel")
                .texture("top", "block/1_basic_refined/3_wood/birch/fancy_birch_wood_topbottom")
                .texture("bottom", "block/1_basic_refined/3_wood/birch/fancy_birch_wood_topbottom")
                .texture("*", "block/2_advanced_refined/7_wood/fancy_birch_wood_panel")
                .register(types);
        VanillaProps.planks()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .name("fancy_birch_wood_arch_panel")
                .texture("top", "block/1_basic_refined/3_wood/birch/fancy_birch_wood_topbottom")
                .texture("bottom", "block/1_basic_refined/3_wood/birch/fancy_birch_wood_topbottom")
                .texture("*", "block/2_advanced_refined/7_wood/fancy_birch_wood_arch_panel")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.ADVANCED_MASONRY_AND_CERAMICS)
                .name("verde_antico_orthostates")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("overlay", "block/2_advanced_refined/1_stone/3_marble/verde_antico_orthostates_overlay")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/verde_antico_orthostates")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("first_style_red_stucco_panel")
                .texture("top", "block/2_advanced_refined/3_plaster/first_style_red_stucco_panel")
                .texture("overlay", "block/2_advanced_refined/3_plaster/first_style_red_stucco_panel")
                .texture("bottom", "block/2_advanced_refined/3_plaster/first_style_red_stucco_panel")
                .texture("*", "block/2_advanced_refined/3_plaster/red_stucco")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("limestone_dwarven_pillar_1")
                .texture("top", "block/2_advanced_refined/1_stone/2_limestone/limestone_dwarven_pillar_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/2_limestone/limestone_dwarven_pillar_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/2_limestone/limestone_dwarven_pillar_1")
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("limestone_dwarven_pillar_2")
                .texture("top", "block/2_advanced_refined/1_stone/2_limestone/limestone_dwarven_pillar_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/2_limestone/limestone_dwarven_pillar_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/2_limestone/limestone_dwarven_pillar_2")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("gothic_checkered_plaster")
                .texture("block/2_advanced_refined/3_plaster/gothic_checkered_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("romanesque_checkered_plaster")
                .texture("block/2_advanced_refined/3_plaster/romanesque_checkered_plaster")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_white_green_gothic_frieze")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_white_romanesque_frieze")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_red_ribbon_frieze")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay","block/2_advanced_refined/3_plaster/white_red_ribbon_frieze")
                .texture("*", "block/2_advanced_refined/3_plaster/white_plaster")
                .register(typesOverlay);
        VanillaProps.stone()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_blue_floral_frieze")
                .texture("top", "block/2_advanced_refined/3_plaster/golden_top")
                .texture("overlay","block/2_advanced_refined/3_plaster/white_blue_floral_frieze")
                .texture("*", "block/2_advanced_refined/3_plaster/white_plaster")
                .register(typesOverlay);
    }
}
