version = 1

test_patterns = [
  "**/src/test/**",
  "**/src/testFixtures/**"
]

exclude_patterns = [
  "**/src/test/**",
  "**/src/testFixtures/**"
]

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "11"