<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.dockbox.hartshorn</groupId>
        <artifactId>hartshorn-platform-support</artifactId>
        <relativePath>../pom.platform.support.xml</relativePath>
        <version>${revision}</version>
    </parent>

    <name>Hartshorn Architecture Rules</name>
    <description>Architecture rules for Hartshorn</description>
    <artifactId>hartshorn-architecture-rules</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-shared</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-shared</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-properties</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-properties</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-profiles</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-profiles</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-spi</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-spi</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-proxy</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-proxy</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-proxy-test-fixtures</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-proxy-javassist</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-proxy-javassist</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-introspect</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-introspect</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-introspect-test-fixtures</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-introspect-reflection</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-introspect-reflection</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-inject</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-inject</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-inject-configurations</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-inject-configurations</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-launchpad</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-launchpad</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-launchpad-kotlin-extensions</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-reporting</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-reporting</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-hsl</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-hsl</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-web</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-web-jetty</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-web-jetty</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-support</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-support</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-test-assertions</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-testsuite</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dockbox.hartshorn</groupId>
            <artifactId>hartshorn-testsuite</artifactId>
            <version>${revision}</version>
            <classifier>tests</classifier>
        </dependency>
        <dependency>
            <groupId>com.tngtech.archunit</groupId>
            <artifactId>archunit-junit6</artifactId>
            <version>1.5.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
