package org.dockbox.hartshorn.web;

import org.dockbox.hartshorn.util.collections.LFUCache;

/**
 * Utility class for working with {@link MediaType media types}. Provides constants for common media
 * types and a method to parse media type strings into {@link MediaType} objects. Commonly requested
 * media types are re-used.
 *
 * @see MediaType
 *
 * @since 0.7.0
 *
 * @author Guus Lieben
 */
public class MediaTypes {

    /**
     * String representation of the {@code application/json} media type.
     * @see #APPLICATION_JSON
     */
    public static final String APPLICATION_JSON_VALUE = "application/json";

    /**
     * {@link MediaType} representation of the {@code application/json} media type.
     *
     * @see <a href="https://www.iana.org/assignments/media-types/application/json">
     * IANA: application/json
     * </a>
     */
    public static final MediaType APPLICATION_JSON = new MediaType("application", "json");

    /**
     * String representation of the {@code application/xml} media type.
     * @see #APPLICATION_XML
     */
    public static final String APPLICATION_XML_VALUE = "application/xml";

    /**
     * {@link MediaType} representation of the {@code application/xml} media type.
     *
     * @see <a href="https://www.iana.org/assignments/media-types/application/xml">
     * IANA: application/xml
     * </a>
     */
    public static final MediaType APPLICATION_XML = new MediaType("application", "xml");

    /**
     * String representation of the {@code text/plain} media type.
     * @see #TEXT_PLAIN
     */
    public static final String TEXT_PLAIN_VALUE = "text/plain";

    /**
     * {@link MediaType} representation of the {@code text/plain} media type.
     */
    public static final MediaType TEXT_PLAIN = new MediaType("text", "plain");

    /**
     * String representation of the {@code text/html} media type.
     * @see #TEXT_HTML
     */
    public static final String TEXT_HTML_VALUE = "text/html";

    /**
     * {@link MediaType} representation of the {@code text/html} media type.
     *
     * @see <a href="https://www.iana.org/assignments/media-types/text/html">
     * IANA: text/html
     * </a>
     */
    public static final MediaType TEXT_HTML = new MediaType("text", "html");

    /**
     * String representation of a wildcard mediatype.
     */
    public static final String WILDCARD_VALUE = "*/*";
    public static final MediaType WILDCARD = new MediaType("*", "*");

    private static final LFUCache<String, MediaType> cachedMediaTypes = new LFUCache<>(
            64,
            MediaTypes::parseInternal
    );

    static {
        cachedMediaTypes.put(APPLICATION_JSON_VALUE, APPLICATION_JSON);
        cachedMediaTypes.put(APPLICATION_XML_VALUE, APPLICATION_XML);
        cachedMediaTypes.put(TEXT_PLAIN_VALUE, TEXT_PLAIN);
        cachedMediaTypes.put(TEXT_HTML_VALUE, TEXT_HTML);
        cachedMediaTypes.put(WILDCARD_VALUE, WILDCARD);
    }

    /**
     * Parses the given string representation into a {@link MediaType}. If the representation was
     * previously used, the cached instance is returned. Otherwise, a new instance is created and
     * cached for future use (based on LFU principles).
     *
     * @param mediaType the string representation of the media type
     *
     * @return a {@link MediaType} instance corresponding to the given string representation
     *
     * @throws IllegalArgumentException if the given string is not a valid media type representation
     */
    public static MediaType parse(String mediaType) {
        // Uncached media types are generated by the LFU cache
        return cachedMediaTypes.get(mediaType);
    }

    private static MediaType parseInternal(String mediaType) {
        String[] parts = mediaType.split(";");
        String[] typeParts = parts[0].trim().split("/");
        if (typeParts.length != 2) {
            throw new IllegalArgumentException("Invalid media type: " + mediaType);
        }
        String type = typeParts[0].trim();
        String subtype = typeParts[1].trim();
        return new MediaType(type, subtype);
    }
}
