package org.dockbox.selene.palswap;
import org.dockbox.selene.core.i18n.common.Language;
import org.dockbox.selene.core.objects.Exceptional;
import org.dockbox.selene.core.objects.item.Item;
import org.dockbox.selene.core.util.SeleneUtils;
import org.dockbox.selene.structures.registry.RegistryIdentifier;

import java.util.Map;

public enum BlockIdentifier implements RegistryIdentifier {

    RED_BRICK_BOX_FRAME_CONNECTED("conquest:stone_full_5:13"),
    FROZEN_COBBLESTONE("conquest:stone_full_1:9", "conquest:stone_fullpartial_1:8", "conquest:stone_corner_2:3", "conquest:stone_verticalslab_2:3", "conquest:stone_arrowslit_2:1"),
    SMOOTH_WHITE_MARBLE("conquest:stone_full_8:8", "conquest:stone_fullpartial_2:2", "conquest:stone_corner_14:1", "conquest:stone_verticalslab_14:1"),
    RED_BRICK_BACK_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_5:12", "conquest:stone_corner_34:0", "conquest:stone_verticalslab_34:0"),
    ENGRAVED_B("conquest:stone_full_8:12"),
    SLATE("conquest:stone_verticalslab_52:2"),
    SEASHELL("conquest:stone_full_25:5"),
    DARK_TUDOR_BACK_SLASH_FRAME("conquest:stone_full_3:11", "conquest:stone_corner_25:3", "conquest:stone_verticalslab_25:3"),
    MUSHROOM("minecraft:red_mushroom_block:0"),
    BLUE_TUDOR_UP_ARROW_FRAME("conquest:stone_full_21:12", "conquest:stone_corner_66:3", "conquest:stone_verticalslab_79:2"),
    BRICK_BLOCK_2("conquest:stone_full_5:14"),
    SMOOTH_ANDESITE("conquest:stone_full_18:14", "conquest:stone_fullpartial_1:1", "conquest:stone_corner_1:2", "conquest:stone_verticalslab_74:1", "conquest:stone_arrowslit_2:2"),
    BIG_BLACK("conquest:stone_full_10:6"),
    SMOOTH_MARBLE_BASE_COLUMN("conquest:stone_full_19:2", "conquest:stone_corner_48:2", "conquest:stone_verticalslab_50:2"),
    DECORATIVE_MOSAIC("conquest:stone_corner_18:2", "conquest:stone_verticalslab_18:2"),
    ENGRAVED_F("conquest:stone_full_9:0"),
    JUNGLE_LEAVES("minecraft:leaves:3"),
    LARGE_SANDSTONE_SLAB("conquest:stone_corner_15:2", "conquest:stone_verticalslab_15:2"),
    MUD_TUDOR_X_FRAME("conquest:stone_full_21:15", "conquest:stone_corner_67:2", "conquest:stone_verticalslab_80:1"),
    WATTLE_TUDOR_V_FRAME("conquest:stone_full_23:0", "conquest:stone_corner_71:3", "conquest:stone_verticalslab_84:2"),
    PLANNING_SIGN_NOT_APPROVED("conquest:stone_full_20:7"),
    ENGRAVED_H("conquest:stone_full_9:2"),
    PILE_OF_BONES("conquest:stone_full_13:11", "conquest:stone_corner_51:1", "conquest:stone_verticalslab_57:1"),
    LIGHT_MORTAR_SLATE("conquest:stone_full_17:14", "conquest:stone_fullpartial_6:0", "conquest:stone_corner_61:3", "conquest:stone_verticalslab_68:3"),
    NETHER_QUARTZ_ORE("minecraft:quartz_ore:0"),
    LIME_STAINED_GLASS("minecraft:stained_glass:5", "minecraft:stained_glass_pane:5"),
    MARBLE("conquest:stone_verticalslab_14:0"),
    TUDOR_X_FRAME("conquest:stone_full_3:3", "conquest:stone_corner_23:3", "conquest:stone_verticalslab_23:3"),
    GOLD_COLUMN("conquest:stone_corner_10:1", "conquest:stone_verticalslab_10:1"),
    SMOOTH_RED_SANDSTONE("conquest:stone_corner_49:3", "conquest:stone_verticalslab_49:3", "minecraft:red_sandstone:2"),
    PURPUR_PILLAR("conquest:stone_corner_50:1", "conquest:stone_verticalslab_50:1"),
    TUDOR_BOX_FRAME("conquest:stone_full_3:6", "conquest:stone_corner_24:2", "conquest:stone_verticalslab_24:2"),
    BRICK_X_FRAME("conquest:stone_full_4:3", "conquest:stone_corner_27:3", "conquest:stone_verticalslab_27:3"),
    RED_AND_WHITE_MARBLE_PATTERN_2("conquest:stone_full_15:11", "conquest:stone_corner_54:0", "conquest:stone_verticalslab_60:0"),
    PRISMARINE_BRICK("conquest:stone_fullpartial_5:0", "conquest:stone_corner_48:3", "minecraft:prismarine:1"),
    DARK_RED_BRICK_BLOCK("conquest:stone_full_6:0"),
    DARK_TUDOR_V_FRAME("conquest:stone_full_3:14", "conquest:stone_corner_26:2", "conquest:stone_verticalslab_26:2"),
    SEASIDE_RED_SANDSTONE("conquest:stone_full_19:4", "conquest:stone_verticalslab_75:3"),
    SPRUCE_WOOD_PLANKS("minecraft:planks:1"),
    LIGHT_BLUE_WALL("conquest:stone_corner_41:2", "conquest:stone_verticalslab_41:2"),
    DARK_TUDOR_BOX_FRAME_VERTICAL_CONNECTION("conquest:stone_full_4:2", "conquest:stone_corner_27:2", "conquest:stone_verticalslab_27:2"),
    ACACIA_LEAVES("minecraft:leaves2:0"),
    INDIAN_MOSAIC("conquest:stone_full_10:11", "conquest:stone_corner_17:3", "conquest:stone_verticalslab_17:3"),
    DARK_TUDOR_UP_ARROW_FRAME("conquest:stone_full_3:13", "conquest:stone_corner_26:1", "conquest:stone_verticalslab_26:1"),
    MAGENTA_WOOL("minecraft:wool:2"),
    LARGE_SANDSTONE_INSCRIBED("conquest:stone_full_10:4"),
    PLANNING_SIGN_UPPERCLASS("conquest:stone_full_20:8"),
    BIG_BLACK_SLAB_INSCRIBED_NO_CTM("conquest:stone_corner_17:1", "conquest:stone_verticalslab_17:1"),
    STONE_BRICK("conquest:stone_fullpartial_4:8", "conquest:stone_corner_45:3", "conquest:stone_verticalslab_45:3", "minecraft:stone_slab:5", "minecraft:stonebrick:0"),
    PURPLE_WOOL("minecraft:wool:10"),
    YELLOW_HARDENED_CLAY("conquest:stone_verticalslab_56:0", "minecraft:stained_hardened_clay:4"),
    STONE_SWORD("minecraft:stone_sword:0"),
    ORNATE_ROMAN_DOOR_BLOCK_NO_CTM("conquest:stone_full_13:6"),
    DIORITE_BRICK("conquest:stone_full_6:5", "conquest:stone_fullpartial_2:3", "conquest:stone_corner_20:1", "conquest:stone_verticalslab_20:1", "conquest:stone_arrowslit_6:0"),
    RED_BRICK_BOX_FRAME_VERTICAL_CONNECTION("conquest:stone_corner_34:1", "conquest:stone_verticalslab_34:1"),
    CLEAN_BLUE_WALLPAPER("conquest:stone_corner_60:1", "conquest:stone_verticalslab_67:1"),
    SMOOTH_SANDSTONE("conquest:stone_corner_44:3", "conquest:stone_verticalslab_44:3", "minecraft:sandstone:2"),
    CYAN_WALL("conquest:stone_corner_41:1", "conquest:stone_verticalslab_41:1"),
    MUD_TUDOR_UP_ARROW_FRAME("conquest:stone_full_22:3", "conquest:stone_corner_68:2", "conquest:stone_verticalslab_81:1"),
    CALCITE("conquest:stone_full_26:11", "conquest:stone_fullpartial_1:9", "conquest:stone_verticalslab_88:0"),
    HEWN_STONE_WITH_STONE_BRICK("conquest:stone_full_1:3"),
    OVERGROWN_COBBLESTONE("conquest:stone_full_2:0", "conquest:stone_fullpartial_1:11", "conquest:stone_corner_3:2", "conquest:stone_verticalslab_3:2", "conquest:stone_arrowslit_3:0"),
    RED_MARBLE("conquest:stone_full_16:4", "conquest:stone_corner_56:1", "conquest:stone_verticalslab_62:1"),
    DWARVEN_RUNES_BLUE_SCHIST("conquest:stone_full_25:13", "conquest:stone_corner_83:0", "conquest:stone_verticalslab_95:3"),
    DIORITE("conquest:stone_verticalslab_54:3", "minecraft:stone:3"),
    PLASTER_WITH_RED_MASONRY_LINES("conquest:stone_full_23:14"),
    RED_BRICK("conquest:stone_full_6:2", "conquest:stone_fullpartial_3:0", "conquest:stone_corner_35:1", "conquest:stone_verticalslab_35:1", "conquest:stone_arrowslit_9:1"),
    PINK_STAINED_GLASS("minecraft:stained_glass:6", "minecraft:stained_glass_pane:6"),
    NETHER_WART_BLOCK("minecraft:nether_wart_block:0"),
    NATURAL_SANDSTONE("conquest:stone_full_14:12", "conquest:stone_verticalslab_53:1"),
    SINDARIN_WALL_1("conquest:stone_full_25:7", "conquest:stone_corner_81:2", "conquest:stone_verticalslab_94:1"),
    BLUE("conquest:stone_full_13:3"),
    BLUE_CONCRETE("minecraft:concrete:11"),
    GILDED_BRONZE_BLOCK("conquest:stone_full_13:8", "conquest:stone_full_18:12", "conquest:stone_fullpartial_3:15"),
    RED_WALL_PAINTING_DESIGN("conquest:stone_full_12:7", "conquest:stone_corner_38:3", "conquest:stone_verticalslab_38:3"),
    DARK_OAK("minecraft:dark_oak_fence:0", "minecraft:dark_oak_fence_gate:0", "minecraft:log2:1"),
    CARVED_RUNES("conquest:stone_full_1:6"),
    IRON_BARS("minecraft:iron_bars:0"),
    LIGHT_GRAY_CONCRETE_POWDER("minecraft:concrete_powder:8"),
    LIME_CONCRETE_POWDER("minecraft:concrete_powder:5"),
    ROMAN_VERTICAL_BRICK("conquest:stone_full_15:1", "conquest:stone_fullpartial_5:6", "conquest:stone_corner_51:3", "conquest:stone_verticalslab_57:3"),
    DRY_STONE_COBBLE("conquest:stone_full_24:15", "conquest:stone_fullpartial_7:6", "conquest:stone_corner_79:2", "conquest:stone_verticalslab_92:1"),
    NETHER_QUARTZ("minecraft:quartz:0"),
    WAVY_RED_ROOF_TILES("conquest:stone_full_21:3", "conquest:stone_corner_90:0", "conquest:stone_verticalslab_102:3"),
    MOSSY_STONE_BRICK("conquest:stone_fullpartial_4:9", "conquest:stone_corner_46:0", "conquest:stone_verticalslab_46:0", "minecraft:stonebrick:1"),
    BLUE_TUDOR_X_FRAME("conquest:stone_full_21:11", "conquest:stone_corner_66:2", "conquest:stone_verticalslab_79:1"),
    BLUE_SCHIST("conquest:stone_corner_90:1", "conquest:stone_verticalslab_71:3"),
    WHITE_IVORY_PILLAR("conquest:stone_corner_65:3", "conquest:stone_verticalslab_78:2"),
    WEATHERED_BLUE_SCHIST("conquest:stone_verticalslab_74:0"),
    RED_TUDOR_V_FRAME("conquest:stone_full_22:9", "conquest:stone_corner_70:0", "conquest:stone_verticalslab_82:3"),
    ENGRAVED_INTERPUNCT("conquest:stone_full_9:4"),
    PLANNING_SIGN_LOWERCLASS("conquest:stone_full_20:9"),
    LIGHT_CLAY_TILE("conquest:stone_corner_22:3", "conquest:stone_verticalslab_22:3"),
    NETHER_WART_BRICK("conquest:stone_fullpartial_5:5", "conquest:stone_corner_50:3", "conquest:stone_verticalslab_50:3"),
    CYAN_WOOL("minecraft:wool:9"),
    DARK_TUDOR_NARROW_BACK_SLASH_FRAME("conquest:stone_full_16:11", "conquest:stone_corner_58:0", "conquest:stone_verticalslab_64:0"),
    BIG_SANDSTONE_BRICKS("conquest:stone_full_6:7"),
    SAND("minecraft:sand:0"),
    SNOW("minecraft:snow:0"),
    PLASTERED_STONE_TILES("conquest:stone_full_1:1", "conquest:stone_fullpartial_6:10", "conquest:stone_corner_64:0", "conquest:stone_verticalslab_71:0"),
    ROMAN_BRICK("conquest:stone_full_6:4", "conquest:stone_fullpartial_3:2", "conquest:stone_corner_35:3", "conquest:stone_verticalslab_35:3", "conquest:stone_arrowslit_9:3"),
    GREEN("conquest:stone_full_13:0"),
    SMOOTH_MARBLE_CAPITAL_COLUMN("conquest:stone_full_19:9", "conquest:stone_corner_50:2", "conquest:stone_verticalslab_75:1"),
    DWARVEN_BLUE_SCHIST_DESIGN("conquest:stone_full_26:1", "conquest:stone_corner_84:0", "conquest:stone_verticalslab_96:3"),
    LARGE_SANDSTONE_INSCRIBED_SLAB_NO_SIDE_CTM("conquest:stone_full_10:5", "conquest:stone_corner_16:1", "conquest:stone_verticalslab_16:1"),
    DARK_SANDSTONE_BIG_SLAB("conquest:stone_corner_78:2", "conquest:stone_verticalslab_91:1"),
    MARBLE_AND_SANDSTONE_BASE("conquest:stone_full_8:4", "conquest:stone_corner_13:1", "conquest:stone_verticalslab_13:1"),
    ICY_STONE_TOP("conquest:stone_full_14:5", "conquest:stone_verticalslab_51:2"),
    ORANGE_STUCCO("conquest:stone_full_12:13", "conquest:stone_corner_40:1", "conquest:stone_verticalslab_40:1"),
    LIME("conquest:stone_full_12:14"),
    RED_BRICK_BOX_FRAME("conquest:stone_full_5:10", "conquest:stone_corner_33:2", "conquest:stone_verticalslab_33:2"),
    BLUE_MARBLE_BASE_COLUMN("conquest:stone_full_7:7", "conquest:stone_corner_9:2", "conquest:stone_verticalslab_9:2"),
    ACACIA_WOOD_PLANKS("minecraft:planks:4"),
    SANDSTONE_CORINTHIAN("conquest:stone_full_8:1"),
    LIGHT_CLAY_TILE_BLOCK("conquest:stone_full_18:1"),
    WHITE_PLASTER_DESIGN("conquest:stone_full_26:9"),
    SNOWY_GRANITE("conquest:stone_full_19:5", "conquest:stone_verticalslab_76:0"),
    TUDOR_BOX_FRAME_VERTICAL_CONNECTION("conquest:stone_full_3:9", "conquest:stone_corner_25:1", "conquest:stone_verticalslab_25:1"),
    ROMAN_MOSAIC("conquest:stone_full_10:10", "conquest:stone_corner_17:2", "conquest:stone_verticalslab_17:2"),
    ORANGE_PLASTER("conquest:stone_full_11:4", "conquest:stone_corner_63:2", "conquest:stone_verticalslab_70:2"),
    DARK_COBBLESTONE("conquest:stone_full_17:3", "conquest:stone_fullpartial_5:14", "conquest:stone_corner_59:3", "conquest:stone_verticalslab_66:0"),
    POLYCHROME_CORINTHIAN("conquest:stone_full_15:6"),
    DARK_COBBLE_SANDSTONE("conquest:stone_full_17:13", "conquest:stone_fullpartial_5:15", "conquest:stone_corner_61:2", "conquest:stone_verticalslab_68:2"),
    MARBLE_BASE("conquest:stone_full_8:6", "conquest:stone_corner_13:3", "conquest:stone_verticalslab_13:3"),
    DARK_RED_BRICK_BOX_FRAME_VERTICAL_CONNECTION("conquest:stone_corner_32:0", "conquest:stone_verticalslab_32:0"),
    DARK_GRAY_STONEBRICK("conquest:stone_full_23:13", "conquest:stone_fullpartial_6:15", "conquest:stone_corner_75:0", "conquest:stone_verticalslab_87:3"),
    WHITE_WOOL("minecraft:wool:0"),
    CORINTHIAN_CAPITAL("conquest:stone_corner_12:1", "conquest:stone_verticalslab_12:1"),
    TUDOR_BACK_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_3:8", "conquest:stone_corner_25:0", "conquest:stone_verticalslab_25:0"),
    WATTLE_TUDOR_UP_ARROW_FRAME("conquest:stone_full_22:15", "conquest:stone_corner_71:2", "conquest:stone_verticalslab_84:1"),
    DARK_RED_BRICK_NARROW_FORWARD_SLASH_FRAME("conquest:stone_full_17:0", "conquest:stone_corner_59:1", "conquest:stone_verticalslab_65:1"),
    ROMAN_BRICK_AND_SANDSTONE("conquest:stone_full_16:7", "conquest:stone_corner_57:0", "conquest:stone_verticalslab_63:0"),
    WATTLE_TUDOR_FORWARD_SLASH_FRAME("conquest:stone_full_22:12", "conquest:stone_corner_70:3", "conquest:stone_verticalslab_83:2"),
    GRAY_WOOL("minecraft:wool:7"),
    COARSE_DIRT("minecraft:dirt:1"),
    OBSIDIAN("conquest:stone_verticalslab_55:1", "minecraft:obsidian:0"),
    BLACK_MARBLE_COLUMN("conquest:stone_corner_46:2", "conquest:stone_verticalslab_46:2"),
    SANDSTONE_COBBLE("conquest:stone_full_6:11", "conquest:stone_fullpartial_2:6", "conquest:stone_corner_21:0", "conquest:stone_verticalslab_21:0", "conquest:stone_arrowslit_6:3"),
    DWARVEN_PILLAR_BLUE_SCHIST_2("conquest:stone_full_26:0", "conquest:stone_corner_83:3", "conquest:stone_verticalslab_96:2"),
    GREEN_WOOL("minecraft:wool:13"),
    DIRTY_SANDSTONE_COBBLE("conquest:stone_full_24:3", "conquest:stone_fullpartial_7:1", "conquest:stone_corner_76:2", "conquest:stone_verticalslab_89:1"),
    CHISELED_SANDSTONE("conquest:stone_full_6:10"),
    TUDOR_UP_ARROW_FRAME("conquest:stone_full_3:4", "conquest:stone_corner_24:0", "conquest:stone_verticalslab_24:0"),
    LIGHT_BLUE_PLASTER("conquest:stone_full_24:14", "conquest:stone_fullpartial_7:5", "conquest:stone_corner_79:1", "conquest:stone_verticalslab_92:0"),
    CLEAN_RED_WALLPAPER("conquest:stone_corner_61:1", "conquest:stone_verticalslab_68:1"),
    ELVEN_PILLAR_2("conquest:stone_full_19:12", "conquest:stone_corner_65:0", "conquest:stone_verticalslab_77:3"),
    OXIDIZED_COPPER_ROOF("conquest:stone_full_14:3"),
    GRAY_TUDOR_UP_ARROW_FRAME("conquest:stone_full_24:2", "conquest:stone_corner_76:1", "conquest:stone_verticalslab_89:0"),
    PURPUR_BLOCK("minecraft:purpur_block:0"),
    DARK_TUDOR_NARROW_FORWARD_SLASH_FRAME("conquest:stone_full_16:10", "conquest:stone_corner_57:3", "conquest:stone_verticalslab_63:3"),
    YELLOW_WOOL("minecraft:wool:4"),
    BLUE_TUDOR_BACK_SLASH_FRAME("conquest:stone_full_21:10", "conquest:stone_corner_66:1", "conquest:stone_verticalslab_79:0"),
    MARBLE_CAPITAL_COLUMN("conquest:stone_full_7:14", "conquest:stone_corner_11:3", "conquest:stone_verticalslab_11:3"),
    ENGRAVED_G("conquest:stone_full_9:1"),
    ELVEN_WALL_4("conquest:stone_full_25:0", "conquest:stone_corner_79:3", "conquest:stone_verticalslab_92:2"),
    DARK_TUDOR_FORWARD_SLASH_FRAME("conquest:stone_full_3:10", "conquest:stone_corner_25:2", "conquest:stone_verticalslab_25:2"),
    EMERALD("minecraft:emerald:0"),
    DARK_RED_BRICK_X_FRAME("conquest:stone_full_4:12", "conquest:stone_corner_30:0", "conquest:stone_verticalslab_30:0"),
    BASALT("conquest:stone_verticalslab_75:2"),
    ENDSTONE("conquest:stone_verticalslab_54:0"),
    OAK("minecraft:fence:0", "minecraft:log:0"),
    ORNATE_ROMAN_DOOR_BLOCK("conquest:stone_full_13:5", "conquest:stone_corner_42:1", "conquest:stone_corner_42:2", "conquest:stone_verticalslab_42:1", "conquest:stone_verticalslab_42:2"),
    DECORATIVE_MOSIAC("conquest:stone_full_11:5"),
    WATTLE_TUDOR_BACK_SLASH_FRAME("conquest:stone_full_22:13", "conquest:stone_corner_71:0", "conquest:stone_verticalslab_83:3"),
    RED_CORAL("conquest:stone_full_13:13"),
    FANCY_TUDOR__FRAME_2("conquest:stone_full_24:5"),
    ORANGE_STAINED_GLASS("minecraft:stained_glass:1", "minecraft:stained_glass_pane:1"),
    TUDOR_NARROW_BACK_SLASH_FRAME("conquest:stone_full_16:9", "conquest:stone_corner_57:2", "conquest:stone_verticalslab_63:2"),
    MAGENTA_CONCRETE("minecraft:concrete:2"),
    RED_SAND("minecraft:sand:1"),
    ELVEN_PILLAR_1("conquest:stone_full_19:10", "conquest:stone_corner_64:2", "conquest:stone_verticalslab_77:1"),
    MARBLE_COLUMN("conquest:stone_full_8:10", "conquest:stone_corner_11:2", "conquest:stone_verticalslab_11:2"),
    WHITE_PLASTER_DESIGN_2("conquest:stone_full_26:10"),
    ELVEN_CARVED_WOOD_WALL_1("conquest:stone_full_23:8", "conquest:stone_corner_73:3", "conquest:stone_verticalslab_86:2"),
    LARGE_SANDSTONE_SLAB_NO_SIDE_CTM("conquest:stone_full_10:3", "conquest:stone_corner_15:3", "conquest:stone_verticalslab_15:3", "conquest:stone_arrowslit_5:2"),
    GRAY_TUDOR_WALL_V("conquest:stone_corner_77:3", "conquest:stone_verticalslab_90:2"),
    WHITE_HARDENED_CLAY("conquest:stone_verticalslab_55:2", "minecraft:stained_hardened_clay:0"),
    POLISHED_GRANITE("conquest:stone_fullpartial_4:0", "conquest:stone_corner_43:2", "conquest:stone_verticalslab_43:2", "minecraft:stone:2"),
    OAK_LEAVES("minecraft:leaves:0"),
    WORN_PEACH_PLASTER("conquest:stone_full_24:6", "conquest:stone_fullpartial_7:2", "conquest:stone_corner_77:1", "conquest:stone_verticalslab_90:0"),
    YELLOW_TUDOR_BOX_FRAME("conquest:stone_full_24:10", "conquest:stone_corner_78:1", "conquest:stone_verticalslab_91:0"),
    POOR_ROMAN_BRICK("conquest:stone_fullpartial_3:9"),
    DARK_TUDOR_BACK_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_4:1", "conquest:stone_corner_27:1", "conquest:stone_verticalslab_27:1"),
    DWARVEN_PILLAR_BLUE_SCHIST_1("conquest:stone_full_25:14", "conquest:stone_corner_83:1", "conquest:stone_verticalslab_96:0"),
    MOSSY_STONE("conquest:stone_full_14:6", "conquest:stone_verticalslab_51:3"),
    RED_CONCRETE("minecraft:concrete:14"),
    COAL_ORE("minecraft:coal_ore:0"),
    DARK_ROMAN_BRICK("conquest:stone_full_16:5", "conquest:stone_fullpartial_5:13", "conquest:stone_corner_56:2", "conquest:stone_verticalslab_62:2"),
    RED_HARDENED_CLAY("conquest:stone_verticalslab_56:3", "minecraft:stained_hardened_clay:14"),
    YELLOW_TUDOR_FORWARD_SLASH_FRAME("conquest:stone_full_23:3", "conquest:stone_corner_72:2", "conquest:stone_verticalslab_85:1"),
    HARAD_ORANGE("conquest:stone_full_25:2"),
    RED_TILES("conquest:stone_full_3:0", "conquest:stone_fullpartial_2:0", "conquest:stone_corner_6:1", "conquest:stone_verticalslab_6:1"),
    DARK_SANDSTONE_BIG("conquest:stone_full_24:11"),
    BLACK_WALL("conquest:stone_corner_42:0", "conquest:stone_verticalslab_42:0"),
    DARK_RED_BRICK_BOX_FRAME_CONNECTED("conquest:stone_full_5:4"),
    LIGHT_BLUE_WOOL("minecraft:wool:3"),
    GLASS("minecraft:glass_pane:0"),
    SANDSTONE_BASE_COLUMN("conquest:stone_full_7:1", "conquest:stone_corner_7:2", "conquest:stone_verticalslab_7:2"),
    DARK_RED_BRICK_NARROW_BACK_SLASH_FRAME("conquest:stone_full_17:1", "conquest:stone_corner_59:2", "conquest:stone_verticalslab_65:2"),
    COLORFUL_FISHSCALE_COBBLE("conquest:stone_full_25:3", "conquest:stone_corner_80:2", "conquest:stone_verticalslab_93:1"),
    PURPLE_CONCRETE_POWDER("minecraft:concrete_powder:10"),
    ICY_STONE("conquest:stone_full_14:4", "conquest:stone_verticalslab_51:1"),
    BRICK_FORWARD_SLASH_FRAME("conquest:stone_full_4:4", "conquest:stone_corner_28:0", "conquest:stone_verticalslab_28:0"),
    BIRCH_LEAVES("minecraft:leaves:2"),
    WEATHERED_GRANITE("conquest:stone_verticalslab_75:0"),
    BRICK_BACK_SLASH_FRAME("conquest:stone_full_4:5", "conquest:stone_corner_28:1", "conquest:stone_verticalslab_28:1"),
    LIGHT_BROWN_DRY_CLAY("conquest:stone_full_14:15"),
    GRASS_BLOCK("minecraft:grass:0"),
    GOLD_MARBLE_CAPITAL_COLUMN("conquest:stone_full_7:10", "conquest:stone_corner_10:2", "conquest:stone_verticalslab_10:2"),
    GRASS_PATH("minecraft:grass_path:0"),
    BLOCK_OF_QUARTZ("minecraft:quartz_block:0"),
    BLACK_CONCRETE("minecraft:concrete:15"),
    BROWN_DRY_CLAY("conquest:stone_full_15:0"),
    POLYCHROME_ARCHITRAVE_WITH_LEGIONARIES("conquest:stone_full_15:4", "conquest:stone_corner_52:1", "conquest:stone_verticalslab_58:1"),
    CHALK("conquest:stone_full_18:5", "conquest:stone_verticalslab_72:2"),
    SINDARIN_WALL_5("conquest:stone_full_25:11", "conquest:stone_corner_82:2", "conquest:stone_verticalslab_95:1"),
    MAGENTA_STAINED_GLASS("minecraft:stained_glass:2", "minecraft:stained_glass_pane:2"),
    ORANGE_SANDSTONE("conquest:stone_full_18:6", "conquest:stone_verticalslab_72:3"),
    RED_SANDSTONE_CAPITAL_COLUMN("conquest:stone_full_7:4", "conquest:stone_corner_8:2", "conquest:stone_verticalslab_8:2"),
    ENGRAVED_N("conquest:stone_full_9:8"),
    BIRCH_WOOD_PLANKS("minecraft:planks:2"),
    CYAN("conquest:stone_full_13:1"),
    WAVY_BLUE_ROOF_TILES("conquest:stone_full_21:2", "conquest:stone_corner_89:0", "conquest:stone_verticalslab_101:3"),
    GRAY_IVORY("conquest:stone_full_19:13"),
    MIXED_CLAY_TILE("conquest:stone_corner_22:2", "conquest:stone_verticalslab_22:2"),
    GRAY_TUDOR_V_FRAME("conquest:stone_full_24:8"),
    CLEAN_GREEN_WALLPAPER("conquest:stone_corner_60:3", "conquest:stone_verticalslab_67:3"),
    ORANGE_RED_BRICK("conquest:stone_full_23:11", "conquest:stone_fullpartial_6:13", "conquest:stone_corner_74:2", "conquest:stone_verticalslab_87:1"),
    DECORATIVE_DARK_STONE_PILLAR("conquest:stone_corner_64:3", "conquest:stone_verticalslab_77:2"),
    CLAY_TILE_BLOCK("conquest:stone_full_17:15"),
    CLEAN_MAGENTA_STUCCO("conquest:stone_full_10:15", "conquest:stone_corner_62:1", "conquest:stone_verticalslab_69:1"),
    SEASHELL_WALL("conquest:stone_fullpartial_7:9", "conquest:stone_corner_81:0", "conquest:stone_verticalslab_93:3"),
    MAGENTA("conquest:stone_full_12:2"),
    BROWN_GRAY_WOOD_SHINGLES("conquest:stone_full_20:14", "conquest:stone_corner_88:1", "conquest:stone_verticalslab_101:0"),
    BIRCH_WOOD("minecraft:birch_stairs:0", "minecraft:wooden_slab:2"),
    LARGE_SANDSTONE("conquest:stone_full_10:2"),
    YELLOW_TUDOR_UP_ARROW_FRAME("conquest:stone_full_23:6", "conquest:stone_corner_73:1", "conquest:stone_verticalslab_86:0"),
    GOTHIC_SANDSTONE_COLUMN("conquest:stone_full_2:6", "conquest:stone_corner_14:0", "conquest:stone_verticalslab_4:1"),
    BROWN_ROOF_TILES("conquest:stone_full_14:2", "conquest:stone_corner_84:3", "conquest:stone_verticalslab_97:2"),
    BRICK_UP_ARROW_FRAME("conquest:stone_full_4:6", "conquest:stone_corner_28:2", "conquest:stone_verticalslab_28:2"),
    SANDSTONE_WITH_INSCRIPTIONS("conquest:stone_full_6:14", "conquest:stone_corner_21:3", "conquest:stone_verticalslab_21:3"),
    GRAY_CONCRETE_POWDER("minecraft:concrete_powder:7"),
    TAN_SANDSTONE("conquest:stone_full_18:4", "conquest:stone_verticalslab_72:1"),
    PRISMARINE("conquest:stone_verticalslab_48:2", "minecraft:prismarine:0"),
    RED_SANDSTONE("conquest:stone_full_18:7", "conquest:stone_fullpartial_5:2", "conquest:stone_corner_49:1", "conquest:stone_verticalslab_49:1", "conquest:stone_verticalslab_73:0", "minecraft:red_sandstone:0", "minecraft:stone_slab2:0"),
    MAGENTA_CONCRETE_POWDER("minecraft:concrete_powder:2"),
    ELVEN_CLEAN_PILLAR("conquest:stone_corner_65:1", "conquest:stone_verticalslab_78:0"),
    LARGE_SANDSTONE_INSCRIBED_SLAB("conquest:stone_corner_16:0", "conquest:stone_verticalslab_16:0"),
    BRICK_NARROW_FORWARD_SLASH_FRAME("conquest:stone_full_16:14", "conquest:stone_corner_58:3", "conquest:stone_verticalslab_64:3"),
    DARK_SANDSTONE_BRICK("conquest:stone_fullpartial_3:6"),
    SPRUCE("minecraft:log:1", "minecraft:spruce_fence:0", "minecraft:spruce_fence_gate:0"),
    ENGRAVED_P("conquest:stone_full_9:10"),
    SMOOTH_LIMESTONE("conquest:stone_verticalslab_74:2"),
    OXIDIZED_COPPER("conquest:stone_verticalslab_97:0"),
    ENGRAVED_ELVEN_DESIGN_1("conquest:stone_full_25:12", "conquest:stone_corner_82:3", "conquest:stone_verticalslab_95:2"),
    LIGHT_BLUE_CONCRETE_POWDER("minecraft:concrete_powder:3"),
    BIG_BLACK_SLAB_INSCRIBED("conquest:stone_corner_17:0", "conquest:stone_verticalslab_17:0"),
    NETHER_BRICK_COLUMN("conquest:stone_full_2:11", "conquest:stone_corner_5:1", "conquest:stone_verticalslab_5:1"),
    RED_MARBLE_BASE_COLUMN("conquest:stone_full_7:3", "conquest:stone_corner_8:1", "conquest:stone_verticalslab_8:1"),
    SINDARIN("conquest:stone_full_25:6"),
    SINDARIN_WALL("conquest:stone_corner_81:1", "conquest:stone_verticalslab_94:0"),
    TAN_STUCCO("conquest:stone_full_11:13", "conquest:stone_fullpartial_3:4", "conquest:stone_corner_36:1", "conquest:stone_verticalslab_36:1"),
    LIGHT_RED("conquest:stone_full_12:11"),
    BROWN_STAINED_GLASS("minecraft:stained_glass:12", "minecraft:stained_glass_pane:12"),
    SMOOTH_CALCITE("conquest:stone_full_26:13", "conquest:stone_fullpartial_2:9"),
    GRAVEL("minecraft:gravel:0"),
    CHISELED_STONE("conquest:stone_full_2:9", "conquest:stone_corner_4:3", "conquest:stone_verticalslab_4:3"),
    MARBLE_SMALL_CHECKER_PATTERN("conquest:stone_full_15:9", "conquest:stone_corner_53:2", "conquest:stone_verticalslab_59:2"),
    TRAVERTINE_BRICK("conquest:stone_full_6:6", "conquest:stone_fullpartial_2:4", "conquest:stone_corner_20:2", "conquest:stone_verticalslab_20:2", "conquest:stone_arrowslit_6:1"),
    FANCY_TUDOR_WALL_2("conquest:stone_corner_77:0", "conquest:stone_verticalslab_89:3"),
    ORANGE_CONCRETE_POWDER("minecraft:concrete_powder:1"),
    BLUE_STAINED_GLASS("minecraft:stained_glass:11", "minecraft:stained_glass_pane:11"),
    MOSSY_WHITE("conquest:stone_full_17:2"),
    PLANNING_SIGN_OTHER("conquest:stone_full_20:3"),
    COAL("minecraft:coal_block:0"),
    CIRCULAR_CARVED_STONE_FLOOR("conquest:stone_full_26:2", "conquest:stone_corner_1:3", "conquest:stone_verticalslab_76:2"),
    ELVEN_CARVED_WOOD_WALL_2("conquest:stone_full_23:9", "conquest:stone_corner_74:0", "conquest:stone_verticalslab_86:3"),
    BLUE_CORAL("conquest:stone_full_13:15"),
    LIGHT_RED_WALL("conquest:stone_corner_39:3", "conquest:stone_verticalslab_39:3"),
    YELLOW_COBBLESTONE_PLASTER("conquest:stone_full_24:9", "conquest:stone_fullpartial_7:4", "conquest:stone_corner_78:0", "conquest:stone_verticalslab_90:3"),
    UNCUT_MARBLE("conquest:stone_verticalslab_52:3"),
    PLANNING_SIGN_NAME("conquest:stone_full_20:1"),
    RED_STUCCO("conquest:stone_full_12:10", "conquest:stone_corner_39:2", "conquest:stone_verticalslab_39:2"),
    GRAY_AND_PINK_GRANITE("conquest:stone_verticalslab_53:0"),
    DARK_PRISMARINE("conquest:stone_fullpartial_5:1", "conquest:stone_corner_49:0", "conquest:stone_verticalslab_49:0"),
    OAK_WOOD("minecraft:wooden_slab:0"),
    LIGHT_RED_ROOF_TILES("conquest:stone_full_20:15", "conquest:stone_corner_88:2", "conquest:stone_verticalslab_101:1"),
    SPONGE("minecraft:sponge:0"),
    RED_TUDOR_UP_ARROW_FRAME("conquest:stone_full_22:8", "conquest:stone_corner_69:3", "conquest:stone_verticalslab_82:2"),
    WHITE_STUCCO("conquest:stone_full_11:12"),
    GREEN_WALL("conquest:stone_corner_41:0", "conquest:stone_verticalslab_41:0"),
    POLYCHROME_CORINTHIAN_CAPITAL("conquest:stone_corner_52:3", "conquest:stone_verticalslab_48:3", "conquest:stone_verticalslab_58:3"),
    CLEAN_WHITE_PLASTER("conquest:stone_full_11:2", "conquest:stone_fullpartial_6:5", "conquest:stone_corner_63:0", "conquest:stone_verticalslab_70:0"),
    SANDSTONE_CORNICE("conquest:stone_corner_12:3", "conquest:stone_verticalslab_12:3"),
    DARK_RED_BRICK_V_FRAME("conquest:stone_full_5:0", "conquest:stone_corner_31:0", "conquest:stone_verticalslab_31:0"),
    STONE("conquest:stone_full_2:10", "conquest:stone_fullpartial_1:2", "conquest:stone_verticalslab_54:1", "minecraft:stone:0", "minecraft:stone_slab:0"),
    OVERGROWN_STONE_BRICK("conquest:stone_full_2:2"),
    HARAD_ORANGE_WALL("conquest:stone_fullpartial_7:8", "conquest:stone_corner_80:1", "conquest:stone_verticalslab_93:0"),
    BLUE_ROOF_TILES("conquest:stone_corner_84:2", "conquest:stone_verticalslab_97:1", "minecraft:stained_hardened_clay:11"),
    GOLD_MARBLE_BASE_COLUMN("conquest:stone_full_7:11", "conquest:stone_corner_10:3", "conquest:stone_verticalslab_10:3"),
    ROUGH_GRANITE("conquest:stone_verticalslab_73:1"),
    MOSSY_STONE_TOP("conquest:stone_full_14:7", "conquest:stone_verticalslab_52:0"),
    GRANITE("conquest:stone_verticalslab_54:2", "minecraft:stone:1"),
    JUNGLE("minecraft:jungle_fence:0", "minecraft:jungle_fence_gate:0", "minecraft:log:3"),
    ENGRAVED_O("conquest:stone_full_9:9"),
    ENGRAVED_T("conquest:stone_full_9:14"),
    RED_BRICK_NARROW_BACK_SLASH_FRAME("conquest:stone_full_16:13", "conquest:stone_corner_58:2", "conquest:stone_verticalslab_64:2"),
    ELVEN_CARVED_WOOD_WALL_3("conquest:stone_full_23:10", "conquest:stone_corner_74:1", "conquest:stone_verticalslab_87:0"),
    SINDARIN_WALL_4("conquest:stone_full_25:10", "conquest:stone_corner_82:1", "conquest:stone_verticalslab_95:0"),
    MARBLE_PEDESTAL("conquest:stone_full_1:14", "conquest:stone_corner_4:0", "conquest:stone_verticalslab_4:0"),
    RED_TUDOR_FORWARD_SLASH_FRAME("conquest:stone_full_22:5", "conquest:stone_corner_69:0", "conquest:stone_verticalslab_81:3"),
    ENGRAVED_M("conquest:stone_full_9:7"),
    LARGE_MARBLE("conquest:stone_full_10:0"),
    SANDSTONE_CORNICE_BLOCK("conquest:stone_full_8:2"),
    JUNGLE_WOOD_PLANKS("minecraft:planks:3"),
    HEWN_STONE_TILES("conquest:stone_full_1:4", "conquest:stone_corner_63:3", "conquest:stone_verticalslab_70:3"),
    RUSTY_IRON_BLOCK("conquest:stone_arrowslit_8:1"),
    CHISELED_RED_SANDSTONE("conquest:stone_corner_49:2", "conquest:stone_verticalslab_49:2", "minecraft:red_sandstone:1"),
    GRAY_ROOF_TILES("conquest:stone_full_14:1", "conquest:stone_corner_85:2", "conquest:stone_verticalslab_98:1", "minecraft:stained_hardened_clay:7"),
    DIAGONAL_CHECKERED_MARBLE_PATTERN("conquest:stone_full_15:13", "conquest:stone_corner_54:2", "conquest:stone_verticalslab_60:2"),
    SANDSTONE("conquest:stone_fullpartial_1:3", "conquest:stone_fullpartial_4:4", "conquest:stone_corner_44:1", "conquest:stone_verticalslab_44:1", "minecraft:sandstone:0", "minecraft:stone_slab:1"),
    CLIFF_STONE("conquest:stone_full_17:5", "conquest:stone_verticalslab_66:2"),
    POLISHED_DIORITE("conquest:stone_fullpartial_4:1", "conquest:stone_corner_43:3", "conquest:stone_verticalslab_43:3", "minecraft:stone:4"),
    BLUE_SANDSTONE_CAPITAL_COLUMN("conquest:stone_full_7:8", "conquest:stone_corner_9:3", "conquest:stone_verticalslab_9:3"),
    GREEN_STAINED_GLASS("minecraft:stained_glass:13", "minecraft:stained_glass_pane:13"),
    BIG_BLACK_INSCRIBED("conquest:stone_full_10:8"),
    WAVY_GRAY_ROOF_TILES("conquest:stone_full_21:4", "conquest:stone_corner_89:2", "conquest:stone_verticalslab_102:1"),
    BROWN_STUCCO("conquest:stone_full_11:15", "conquest:stone_fullpartial_3:5", "conquest:stone_corner_36:3", "conquest:stone_verticalslab_36:3"),
    BRICK_V_FRAME("conquest:stone_full_4:7", "conquest:stone_corner_28:3", "conquest:stone_verticalslab_28:3"),
    LIGHT_GRAY_STAINED_GLASS("minecraft:stained_glass:8", "minecraft:stained_glass_pane:8"),
    RED_MARBLE_CAPITAL_COLUMN("conquest:stone_full_7:2", "conquest:stone_corner_8:0", "conquest:stone_verticalslab_8:0"),
    ENGRAVED_I("conquest:stone_full_9:3"),
    RED_WALL_DESIGN("conquest:stone_full_12:3", "conquest:stone_full_12:4", "conquest:stone_full_12:5", "conquest:stone_full_12:6", "conquest:stone_full_12:8", "conquest:stone_full_12:9", "conquest:stone_corner_37:3", "conquest:stone_corner_38:0", "conquest:stone_corner_38:1", "conquest:stone_corner_38:2", "conquest:stone_corner_39:0", "conquest:stone_corner_39:1", "conquest:stone_verticalslab_37:3", "conquest:stone_verticalslab_38:0", "conquest:stone_verticalslab_38:1", "conquest:stone_verticalslab_38:2", "conquest:stone_verticalslab_39:0", "conquest:stone_verticalslab_39:1"),
    GREEN_CONCRETE_POWDER("minecraft:concrete_powder:13"),
    NATURAL_RED_MOSSY_SANDSTONE("conquest:stone_full_2:15", "conquest:stone_verticalslab_71:2"),
    MIXED_TILE_BLOCK("conquest:stone_full_18:0"),
    DIRT("minecraft:dirt:0"),
    SANDSTONE_BASE("conquest:stone_full_8:3", "conquest:stone_corner_13:0", "conquest:stone_verticalslab_13:0"),
    GRAY_TUDOR_X_FRAME("conquest:stone_full_24:1", "conquest:stone_corner_76:0", "conquest:stone_verticalslab_88:3"),
    PEACH_PLASTER("conquest:stone_full_23:1", "conquest:stone_fullpartial_1:13", "conquest:stone_corner_72:0", "conquest:stone_verticalslab_84:3", "conquest:stone_arrowslit_3:3"),
    CRACKED_STONE_BRICK("conquest:stone_fullpartial_4:10", "conquest:stone_corner_46:1", "conquest:stone_verticalslab_46:1", "minecraft:stonebrick:2"),
    MOSSY_WHITE_ROCK("conquest:stone_verticalslab_65:3"),
    PLANNING_SIGN_APPROVED("conquest:stone_full_19:15"),
    COBBLESTONE_WITH_VINES("conquest:stone_full_2:1", "conquest:stone_fullpartial_1:12", "conquest:stone_corner_3:3", "conquest:stone_verticalslab_3:3", "conquest:stone_arrowslit_3:1"),
    BRICK_BOX_FRAME("conquest:stone_full_4:8", "conquest:stone_corner_29:0", "conquest:stone_verticalslab_29:0"),
    DWARVEN_DESIGN_BLUE_SCHIST("conquest:stone_full_25:15", "conquest:stone_corner_83:2", "conquest:stone_verticalslab_96:1"),
    CHISELED_QUARTZ_BLOCK("minecraft:quartz_block:1"),
    DARK_RED_BRICK_FORWARD_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_5:2", "conquest:stone_corner_31:2", "conquest:stone_verticalslab_31:2"),
    WATTLE_TUDOR_X_FRAME("conquest:stone_full_22:11", "conquest:stone_corner_70:2", "conquest:stone_verticalslab_83:1"),
    CHISELED_QUARTZ("conquest:stone_corner_47:1", "conquest:stone_verticalslab_47:1"),
    CHISELED_STONE_BRICK("conquest:stone_full_2:3"),
    PLANNING_SIGN_WAITTING_APPROVAL("conquest:stone_full_20:6"),
    GREEN_CONCRETE("minecraft:concrete:13"),
    PURPUR("conquest:stone_fullpartial_5:3", "conquest:stone_corner_50:0", "conquest:stone_verticalslab_50:0", "minecraft:purpur_pillar:0", "minecraft:purpur_slab:0", "minecraft:purpur_stairs:0"),
    GREEN_ROOF_TILES("conquest:stone_corner_85:3", "conquest:stone_verticalslab_98:2", "minecraft:stained_hardened_clay:13"),
    MARBLE_CORNICE_BLOCK("conquest:stone_full_8:5", "conquest:stone_corner_13:2", "conquest:stone_verticalslab_13:2"),
    RED_COLUMN("conquest:stone_corner_7:3", "conquest:stone_verticalslab_7:3"),
    FANCY_TUDOR_WALL_1("conquest:stone_corner_76:3", "conquest:stone_verticalslab_89:2"),
    LIME_WOOL("minecraft:wool:5"),
    FLINT_SWORD("minecraft:wooden_sword:0"),
    BIRCH("minecraft:birch_fence:0", "minecraft:birch_fence_gate:0", "minecraft:log:2"),
    SANDSTONE_COLUMN("conquest:stone_corner_7:0", "conquest:stone_verticalslab_7:0"),
    BLUE_MARBLE_CAPITAL_COLUMN("conquest:stone_full_7:6", "conquest:stone_corner_9:1", "conquest:stone_verticalslab_9:1"),
    TUDOR_V_FRAME("conquest:stone_full_3:5", "conquest:stone_corner_24:1", "conquest:stone_verticalslab_24:1"),
    GOLD_SANDSTONE_BASE_COLUMN("conquest:stone_full_7:13", "conquest:stone_corner_11:1", "conquest:stone_verticalslab_11:1"),
    TUDOR_FORWARD_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_3:7", "conquest:stone_corner_24:3", "conquest:stone_verticalslab_24:3"),
    PLANNING_SIGN("conquest:stone_full_20:4"),
    PINK_CONCRETE_POWDER("minecraft:concrete_powder:6"),
    BLUE_TUDOR_BOX_FRAME("conquest:stone_full_21:14", "conquest:stone_corner_67:1", "conquest:stone_verticalslab_80:0"),
    LARGE_MARBLE_SLAB("conquest:stone_corner_15:0", "conquest:stone_verticalslab_15:0"),
    SANDSTONE_FRIEZE("conquest:stone_full_6:13", "conquest:stone_corner_21:2", "conquest:stone_verticalslab_21:2"),
    BLACK_STAINED_GLASS("minecraft:stained_glass:15", "minecraft:stained_glass_pane:15"),
    CLEAN_PURPLE_STUCCO("conquest:stone_full_11:3", "conquest:stone_corner_63:1", "conquest:stone_verticalslab_70:1"),
    FANCY_BRONZE_BLOCK("conquest:stone_full_13:7", "conquest:stone_corner_43:0", "conquest:stone_verticalslab_43:0"),
    ENGRAVED_A("conquest:stone_full_8:11"),
    GOLD_BLOCK_2("conquest:stone_full_13:10"),
    BROWN_CONCRETE_POWDER("minecraft:concrete_powder:12"),
    TERRACOTTA_IMBRICES_AND_TEGULAE("conquest:stone_full_2:5", "conquest:stone_corner_90:2", "conquest:stone_verticalslab_98:0"),
    BLUE_MARBLE("conquest:stone_full_16:0", "conquest:stone_corner_55:1", "conquest:stone_verticalslab_61:1"),
    QUARTZ("conquest:stone_fullpartial_1:4", "conquest:stone_corner_47:0", "conquest:stone_verticalslab_47:0", "minecraft:stone_slab:7"),
    BLUE_TUDOR_V_FRAME("conquest:stone_full_21:13", "conquest:stone_corner_67:0", "conquest:stone_verticalslab_79:3"),
    POLISHED_ANDESITE("conquest:stone_fullpartial_4:2", "conquest:stone_corner_44:0", "conquest:stone_verticalslab_44:0"),
    GRAY_CONCRETE("minecraft:concrete:7"),
    LAPIS_LAZULI_BLOCK_2("conquest:stone_full_1:13"),
    BLACK_MARBLE("conquest:stone_full_15:15", "conquest:stone_corner_55:0", "conquest:stone_verticalslab_61:0"),
    PURPLE_STUCCO("conquest:stone_full_12:0", "conquest:stone_corner_48:1", "conquest:stone_verticalslab_48:1", "minecraft:stained_hardened_clay:10"),
    ENGRAVED_R("conquest:stone_full_9:12"),
    BLUE_WOOL("minecraft:wool:11"),
    BRICK_BACK_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_4:10", "conquest:stone_corner_29:2", "conquest:stone_verticalslab_29:2"),
    BLUE_COLUMN("conquest:stone_corner_9:0", "conquest:stone_verticalslab_9:0"),
    QUARTZ_PILLAR("conquest:stone_corner_47:2", "conquest:stone_verticalslab_47:2"),
    BLOCK_OF_EMERALD("minecraft:emerald_block:0"),
    CARVED_NETHER_BRICK("conquest:stone_full_2:14", "conquest:stone_fullpartial_1:15", "conquest:stone_corner_6:0", "conquest:stone_verticalslab_6:0"),
    TUDOR_BACK_SLASH_FRAME("conquest:stone_full_3:2", "conquest:stone_corner_23:2", "conquest:stone_verticalslab_23:2"),
    RED_TUDOR_BOX_FRAME("conquest:stone_full_22:10", "conquest:stone_corner_70:1", "conquest:stone_verticalslab_83:0"),
    FANCY_TUDOR__FRAME_1("conquest:stone_full_24:4"),
    OLD_COBBLESTONE("conquest:stone_full_1:8", "conquest:stone_fullpartial_1:7", "conquest:stone_corner_2:2", "conquest:stone_verticalslab_2:2", "conquest:stone_arrowslit_2:0"),
    PLANNING_SIGN_SPECIAL("conquest:stone_full_20:5"),
    BRICK_NARROW_BACK_SLASH_FRAME("conquest:stone_full_16:15", "conquest:stone_corner_59:0", "conquest:stone_verticalslab_65:0"),
    DARK_OAK_DOOR("minecraft:dark_oak_door:0"),
    BLUE_MARBLE_WITH_SANDSTONE("conquest:stone_full_6:8", "conquest:stone_full_6:9"),
    CYAN_ROOF_TILES("conquest:stone_corner_85:0", "conquest:stone_verticalslab_97:3", "minecraft:stained_hardened_clay:9"),
    MOSSY_AUBURN_ROOF_TILES("conquest:stone_full_21:6", "conquest:stone_corner_87:1", "conquest:stone_verticalslab_100:0"),
    CARVED_RUNES_CONNECTED("conquest:stone_full_1:7"),
    DARK_SANDSTONE("conquest:stone_full_25:1", "conquest:stone_fullpartial_7:7", "conquest:stone_corner_80:0", "conquest:stone_verticalslab_92:3"),
    DARK_RED_BRICK_UP_ARROW_FRAME("conquest:stone_full_4:15", "conquest:stone_corner_30:3", "conquest:stone_verticalslab_30:3"),
    DARK_OAK_WOOD("minecraft:wooden_slab:5"),
    RED_TUDOR_BACK_SLASH_FRAME("conquest:stone_full_22:6", "conquest:stone_corner_69:1", "conquest:stone_verticalslab_82:0"),
    DARK_RED_BRICK_BOX_FRAME("conquest:stone_full_5:1", "conquest:stone_corner_31:1", "conquest:stone_verticalslab_31:1"),
    MARBLE_COLUMN_BASE("conquest:stone_full_8:9", "conquest:stone_corner_14:2", "conquest:stone_verticalslab_14:2"),
    MOSSY_SANDSTONE("conquest:stone_full_6:12", "conquest:stone_fullpartial_2:7", "conquest:stone_corner_21:1", "conquest:stone_verticalslab_21:1", "conquest:stone_arrowslit_7:0"),
    BRICK("conquest:stone_fullpartial_4:6", "conquest:stone_corner_45:1", "conquest:stone_verticalslab_45:1", "minecraft:stone_slab:4"),
    PINK_MARBLE("conquest:stone_full_16:3", "conquest:stone_corner_56:0", "conquest:stone_verticalslab_62:0"),
    SMOOTH_MARBLE_COLUMN("conquest:stone_full_21:5", "conquest:stone_corner_64:1", "conquest:stone_verticalslab_77:0"),
    PILLAR_QUARTZ_BLOCK("minecraft:quartz_block:2"),
    STONE_COBBLESTONE("conquest:stone_full_2:4"),
    ANDALUSIAN_MOSAIC("conquest:stone_full_10:12", "conquest:stone_corner_18:0", "conquest:stone_verticalslab_18:0"),
    RUINED_STONE_BRICK("conquest:stone_full_26:14", "conquest:stone_fullpartial_2:10"),
    BIG_RED_NETHER_BRICK("conquest:stone_corner_51:0", "conquest:stone_verticalslab_51:0", "minecraft:red_nether_brick:0"),
    DARK_RED_SANDSTONE("conquest:stone_fullpartial_3:10"),
    LIGHT_BLUE("conquest:stone_full_13:2"),
    MUD_BRICK("conquest:stone_fullpartial_3:8"),
    DIRTY_FISHSCALE_COBBLESTONE("conquest:stone_full_1:11", "conquest:stone_fullpartial_1:10", "conquest:stone_corner_3:0", "conquest:stone_verticalslab_3:0", "conquest:stone_arrowslit_2:3"),
    WORN_PLASTER_WITH_RED_MASONRY_LINES("conquest:stone_full_23:7"),
    SANDSTONE_CAPITAL_COLUMN("conquest:stone_full_7:0", "conquest:stone_corner_7:1", "conquest:stone_verticalslab_7:1"),
    SPRUCE_LEAVES("minecraft:leaves:1"),
    SPRUCE_WOOD("minecraft:spruce_stairs:0", "minecraft:wooden_slab:1"),
    BIG_SANDSTONE_BRICK("conquest:stone_fullpartial_2:5", "conquest:stone_corner_20:3", "conquest:stone_verticalslab_20:3", "conquest:stone_arrowslit_6:2"),
    LICHEN_BLUE_SCHIST("conquest:stone_verticalslab_73:2"),
    PURPLE_CONCRETE("minecraft:concrete:10"),
    GILDED_BRONZE_BLOCKVERTICAL("conquest:stone_verticalslab_42:3"),
    GREEN_MARBLE("conquest:stone_full_16:2", "conquest:stone_corner_55:3", "conquest:stone_verticalslab_61:3"),
    LIME_WALL("conquest:stone_corner_40:2", "conquest:stone_verticalslab_40:2"),
    JUNGLE_WOOD("minecraft:wooden_slab:3"),
    WAVY_GOLD_ROOF_TILES("conquest:stone_full_21:7", "conquest:stone_corner_89:1", "conquest:stone_verticalslab_102:0"),
    PORTCULLIS_GROOVE("conquest:stone_full_2:8", "conquest:stone_corner_4:2", "conquest:stone_verticalslab_4:2", "conquest:stone_arrowslit_4:0"),
    ENGRAVED_ELVEN_DESIGN("conquest:stone_full_25:4", "conquest:stone_corner_80:3", "conquest:stone_verticalslab_93:2"),
    PURPLE_STAINED_GLASS("minecraft:stained_glass:10", "minecraft:stained_glass_pane:10"),
    ENGRAVED_L("conquest:stone_full_9:6"),
    MARBLE_CHECKER_PATTERN("conquest:stone_full_15:14", "conquest:stone_corner_54:3", "conquest:stone_verticalslab_60:3"),
    GRAY_STAINED_GLASS("minecraft:stained_glass:7", "minecraft:stained_glass_pane:7"),
    GRAY_TUDOR_BACK_SLASH_FRAME("conquest:stone_full_24:0", "conquest:stone_corner_75:3", "conquest:stone_verticalslab_88:2"),
    STUCCO("conquest:stone_full_10:13", "conquest:stone_fullpartial_2:1", "conquest:stone_corner_18:1", "conquest:stone_verticalslab_18:1"),
    GREYWACKE("conquest:stone_full_19:6", "conquest:stone_verticalslab_76:1"),
    IRON_BLOCK("conquest:stone_fullpartial_4:5", "conquest:stone_corner_6:3", "conquest:stone_corner_45:0", "conquest:stone_verticalslab_6:3", "conquest:stone_verticalslab_45:0"),
    BRICK_FORWARD_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_4:9", "conquest:stone_corner_29:1", "conquest:stone_verticalslab_29:1"),
    PINK_ROOF_TILES("conquest:stone_corner_86:2", "conquest:stone_verticalslab_99:1", "minecraft:stained_hardened_clay:6"),
    GRAY_MARBLE("conquest:stone_full_16:1", "conquest:stone_corner_55:2", "conquest:stone_verticalslab_61:2"),
    DARK_TUDOR_BOX_FRAME("conquest:stone_full_3:15", "conquest:stone_corner_26:3", "conquest:stone_verticalslab_26:3"),
    ENGRAVED_E("conquest:stone_full_8:15"),
    SHALE("conquest:stone_verticalslab_72:0"),
    SANDSTONE_BORDERED_STUCCO("conquest:stone_corner_44:2", "conquest:stone_verticalslab_44:2", "minecraft:sandstone:1"),
    DARK_RED_BRICK_BACK_SLASH_FRAME("conquest:stone_full_4:14", "conquest:stone_corner_30:2", "conquest:stone_verticalslab_30:2"),
    RED_TUDOR_X_FRAME("conquest:stone_full_22:7", "conquest:stone_corner_69:2", "conquest:stone_verticalslab_82:1"),
    WAVY_LIGHT_GRAY_ROOF_TILES("conquest:stone_full_21:8", "conquest:stone_corner_89:3", "conquest:stone_verticalslab_102:2"),
    LIGHT_BROWN_MESA_STONE("conquest:stone_full_14:13", "conquest:stone_verticalslab_53:2"),
    BLUE_AND_YELLOW_MARBLE_PATTERN("conquest:stone_full_15:12", "conquest:stone_corner_54:1", "conquest:stone_verticalslab_60:1"),
    MARBLE_BASE_DESIGN("conquest:stone_full_26:7", "conquest:stone_corner_85:1"),
    HARDENED_CLAY("conquest:stone_verticalslab_57:0", "minecraft:hardened_clay:0"),
    TUDOR_FORWARD_SLASH_FRAME("conquest:stone_full_3:1", "conquest:stone_corner_23:1", "conquest:stone_verticalslab_23:1"),
    RED_WALLPAPER("conquest:stone_full_17:11", "conquest:stone_corner_61:0", "conquest:stone_verticalslab_68:0"),
    ENGRAVED_Q("conquest:stone_full_9:11"),
    RED_BRICK_NARROW_FORWARD_SLASH_FRAME("conquest:stone_full_16:12", "conquest:stone_corner_58:1", "conquest:stone_verticalslab_64:1"),
    BROWN_WOOL("minecraft:wool:12"),
    BROWN_STUCCO_WALL_DESIGN("conquest:stone_full_11:14", "conquest:stone_corner_36:2", "conquest:stone_verticalslab_36:2"),
    GREEN_WALLPAPER("conquest:stone_full_17:9", "conquest:stone_corner_60:2", "conquest:stone_verticalslab_67:2"),
    WHITE_STAINED_GLASS("minecraft:stained_glass:0", "minecraft:stained_glass_pane:0"),
    WORN_DARK_BROWN_PLASTER("conquest:stone_full_24:7", "conquest:stone_fullpartial_7:3", "conquest:stone_corner_77:2", "conquest:stone_verticalslab_90:1"),
    BLACK_AND_WHITE_MARBLE_PATTERN("conquest:stone_full_15:7", "conquest:stone_corner_53:0", "conquest:stone_verticalslab_59:0"),
    RED_AND_WHITE_MARBLE_PATTERN("conquest:stone_full_15:10", "conquest:stone_corner_53:3", "conquest:stone_verticalslab_59:3"),
    LIGHT_BLUE_CONCRETE("minecraft:concrete:3"),
    SANDSTONE_CORINTHIAN_CAPITAL("conquest:stone_corner_12:2", "conquest:stone_verticalslab_12:2"),
    DARK_RED_BRICK("conquest:stone_fullpartial_2:14", "conquest:stone_corner_34:3", "conquest:stone_verticalslab_34:3", "conquest:stone_arrowslit_8:3"),
    BROWN_CONCRETE("minecraft:concrete:12"),
    MAGENTA_STUCCO("conquest:stone_corner_47:3", "conquest:stone_verticalslab_47:3", "minecraft:stained_hardened_clay:2"),
    BLACK("conquest:stone_full_13:4"),
    BROWN_HARDENED_CLAY("conquest:stone_verticalslab_56:2", "minecraft:stained_hardened_clay:12"),
    JACK_O_LANTERN("minecraft:lit_pumpkin:0"),
    DARK_RED_BRICK_FORWARD_SLASH_FRAME("conquest:stone_full_4:13", "conquest:stone_corner_30:1", "conquest:stone_verticalslab_30:1"),
    ROUGH_CALCITE("conquest:stone_full_26:12"),
    WATTLE_TUDOR_BOX_FRAME("conquest:stone_full_22:14", "conquest:stone_corner_71:1", "conquest:stone_verticalslab_84:0"),
    BIG_BLACK_SLAB("conquest:stone_corner_16:2", "conquest:stone_verticalslab_16:2"),
    AUBURN_ROOF_TILES("conquest:stone_full_21:1", "conquest:stone_corner_87:0", "conquest:stone_verticalslab_99:3"),
    PAHOEHOE("conquest:stone_full_14:14", "conquest:stone_verticalslab_53:3"),
    MARBLE_SMALL_DIAGONAL_CHECKER_PATTERN("conquest:stone_full_15:8", "conquest:stone_corner_53:1", "conquest:stone_verticalslab_59:1"),
    GRAY_TILES("conquest:stone_full_19:7", "conquest:stone_corner_4:1", "conquest:stone_verticalslab_76:3"),
    COASTAL_STONE("conquest:stone_full_17:6", "conquest:stone_verticalslab_66:3"),
    CYAN_STAINED_GLASS("minecraft:stained_glass:9", "minecraft:stained_glass_pane:9"),
    LIGHT_GRAY_STUCCO("conquest:stone_fullpartial_4:13", "conquest:stone_corner_48:0", "conquest:stone_verticalslab_48:0", "minecraft:stained_hardened_clay:8"),
    RED_BRICK_BACK_SLASH_FRAME("conquest:stone_full_5:7", "conquest:stone_corner_32:2", "conquest:stone_verticalslab_32:2"),
    LIMESTONE_BIG_SLAB("conquest:stone_corner_78:3", "conquest:stone_verticalslab_91:2"),
    ENGRAVED_V("conquest:stone_full_9:15"),
    MUD_TUDOR_FORWARD_SLASH_FRAME("conquest:stone_full_22:0", "conquest:stone_corner_67:3", "conquest:stone_verticalslab_80:2"),
    WHITE_CONCRETE_POWDER("minecraft:concrete_powder:0"),
    LARGE_MARBLE_SLAB_NO_SIDE_CTM("conquest:stone_full_10:1", "conquest:stone_corner_15:1", "conquest:stone_verticalslab_15:1", "conquest:stone_arrowslit_5:1"),
    BLUE_WALLPAPER("conquest:stone_full_17:7", "conquest:stone_corner_60:0", "conquest:stone_verticalslab_67:0"),
    LIMESTONE_BIG("conquest:stone_full_24:12"),
    DARK_MUD_STONEBRICK("conquest:stone_full_24:13", "conquest:stone_corner_79:0", "conquest:stone_verticalslab_91:3"),
    MUD_TUDOR_BOX_FRAME("conquest:stone_full_22:2", "conquest:stone_corner_68:1", "conquest:stone_verticalslab_81:0"),
    NONE("conquest:stone_full_2:7", "conquest:stone_full_8:7", "conquest:stone_full_15:2", "conquest:torch_0_1:1", "conquest:torch_6_2:1", "conquest:torch_8_2:1", "conquest:torch_10_2:1", "conquest:stone_fullpartial_4:12", "conquest:stone_fullpartial_4:14", "conquest:stone_fullpartial_4:15", "conquest:stone_fullpartial_5:4", "conquest:stone_fullpartial_5:7", "conquest:stone_fullpartial_5:8", "conquest:stone_fullpartial_5:9", "conquest:stone_fullpartial_5:10", "conquest:stone_fullpartial_5:11", "conquest:stone_fullpartial_5:12", "conquest:stone_fullpartial_6:6", "conquest:stone_fullpartial_6:7", "conquest:stone_fullpartial_6:8", "conquest:stone_fullpartial_6:12", "conquest:stone_fullpartial_7:0", "conquest:stone_fullpartial_7:12", "conquest:stone_fullpartial_7:13", "conquest:stone_fullpartial_7:14", "conquest:stone_fullpartial_7:15", "conquest:stone_directionalfullpartial_1:2", "conquest:stone_directionalfullpartial_1:3", "conquest:stone_arrowslit_3:2"),
    MUD_TUDOR_V_FRAME("conquest:stone_full_22:4", "conquest:stone_corner_68:3", "conquest:stone_verticalslab_81:2"),
    GRAY_TUDOR_FORWARD_SLASH_FRAME("conquest:stone_full_23:15", "conquest:stone_corner_75:2", "conquest:stone_verticalslab_88:1"),
    ENGRAVED_S("conquest:stone_full_9:13"),
    CLEAN_YELLOW_STUCCO("conquest:stone_full_11:1", "conquest:stone_fullpartial_6:4", "conquest:stone_corner_62:3", "conquest:stone_verticalslab_69:3"),
    WHITE_IVORY("conquest:stone_full_19:14"),
    RED_BRICK_FORWARD_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_5:11", "conquest:stone_corner_33:3", "conquest:stone_verticalslab_33:3"),
    CORINTHIAN("conquest:stone_full_8:0"),
    ROUGH_MARBLE("conquest:stone_verticalslab_74:3"),
    LIGHT_GRAY_CONCRETE("conquest:stone_arrowslit_7:2", "minecraft:concrete:8"),
    YELLOW_CORAL("conquest:stone_full_13:14"),
    BIG_BLACK_SLAB_NO_SIDE_CTM("conquest:stone_full_10:7", "conquest:stone_corner_16:3", "conquest:stone_verticalslab_16:3", "conquest:stone_arrowslit_5:3"),
    DARK_TUDOR_FORWARD_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_4:0", "conquest:stone_corner_27:0", "conquest:stone_verticalslab_27:0"),
    WET_SLATE("conquest:stone_verticalslab_52:1"),
    ORANGE_CONCRETE("minecraft:concrete:1"),
    RED_WOOL("minecraft:wool:14"),
    BLACK_WALL_DESIGN("conquest:stone_full_12:15", "conquest:stone_corner_40:3", "conquest:stone_verticalslab_40:3"),
    GRAY_WOOD_SHINGLES("conquest:stone_full_20:12", "conquest:stone_corner_87:3", "conquest:stone_verticalslab_100:2"),
    LIGHT_GREEN_ROOF_TILES("conquest:stone_corner_86:1", "conquest:stone_verticalslab_99:0", "minecraft:stained_hardened_clay:5"),
    LIME_CONCRETE("minecraft:concrete:5"),
    LIGHT_GRAY_WOOL("minecraft:wool:8"),
    ACACIA("minecraft:acacia_fence:0", "minecraft:acacia_fence_gate:0", "minecraft:log2:0"),
    ORANGE_WALL_DESIGN("conquest:stone_full_12:12", "conquest:stone_corner_40:0", "conquest:stone_verticalslab_40:0"),
    YELLOW_TUDOR_X_FRAME("conquest:stone_full_23:2", "conquest:stone_corner_72:1", "conquest:stone_verticalslab_85:0"),
    MARBLE_BASE_DESIGN_2("conquest:stone_full_26:8", "conquest:stone_corner_90:3"),
    ENGRAVED_D("conquest:stone_full_8:14"),
    CYAN_CONCRETE_POWDER("minecraft:concrete_powder:9"),
    STONE_URN("conquest:stone_full_18:13"),
    RED_ROOF_TILES("conquest:stone_full_14:0", "conquest:stone_full_21:0", "conquest:stone_corner_86:3", "conquest:stone_corner_88:3", "conquest:stone_verticalslab_99:2", "conquest:stone_verticalslab_101:2"),
    SMALL_DIORITE_BRICK("conquest:stone_fullpartial_3:7"),
    RED_CONCRETE_POWDER("minecraft:concrete_powder:14"),
    DARK_TUDOR_X_FRAME("conquest:stone_full_3:12", "conquest:stone_corner_26:0", "conquest:stone_verticalslab_26:0"),
    MOSSY_COBBLESTONE("conquest:stone_full_1:15", "conquest:stone_fullpartial_4:7", "conquest:stone_corner_3:1", "conquest:stone_corner_45:2", "conquest:stone_verticalslab_3:1", "conquest:stone_verticalslab_45:2"),
    SINDARIN_WALL_2("conquest:stone_full_25:8", "conquest:stone_corner_81:3", "conquest:stone_verticalslab_94:2"),
    YELLOW_CONCRETE("minecraft:concrete:4"),
    POLYCHROME_ARCHITRAVE_2("conquest:stone_full_15:5", "conquest:stone_corner_52:2", "conquest:stone_verticalslab_58:2"),
    NETHER_BRICK("conquest:stone_full_2:13", "conquest:stone_fullpartial_4:11", "conquest:stone_corner_46:3", "conquest:stone_verticalslab_46:3", "minecraft:nether_brick:0", "minecraft:nether_brick_fence:0", "minecraft:netherbrick:0", "minecraft:stone_slab:6"),
    COBBLESTONE("conquest:stone_fullpartial_4:3", "conquest:stone_corner_1:1", "conquest:stone_verticalslab_1:1", "conquest:stone_arrowslit_1:1", "minecraft:cobblestone:0", "minecraft:cobblestone_wall:0", "minecraft:stone_slab:3", "minecraft:stone_stairs:0"),
    MUD_TUDOR_BACK_SLASH_FRAME("conquest:stone_full_22:1", "conquest:stone_corner_68:0", "conquest:stone_verticalslab_80:3"),
    RUSTY_IRON("conquest:stone_fullpartial_2:12", "conquest:stone_corner_23:0", "conquest:stone_verticalslab_23:0"),
    GRAY_HARDENED_CLAY("conquest:stone_verticalslab_56:1"),
    SINDARIN_WALL_3("conquest:stone_full_25:9", "conquest:stone_corner_82:0", "conquest:stone_verticalslab_94:3"),
    MOSSY_DARK_RED_BRICK("conquest:stone_full_6:1", "conquest:stone_fullpartial_2:15", "conquest:stone_corner_35:0", "conquest:stone_verticalslab_35:0", "conquest:stone_arrowslit_9:0"),
    POLYCHROME_ARCHITRAVE("conquest:stone_full_15:3", "conquest:stone_corner_52:0", "conquest:stone_verticalslab_58:0"),
    BIG_NETHER_BRICK("conquest:stone_full_2:12", "conquest:stone_fullpartial_1:14", "conquest:stone_corner_5:2", "conquest:stone_verticalslab_5:2", "conquest:stone_arrowslit_4:1"),
    ORANGE_HARDENED_CLAY("conquest:stone_verticalslab_55:3", "minecraft:stained_hardened_clay:1"),
    YELLOW_CONCRETE_POWDER("minecraft:concrete_powder:4"),
    LIGHT_BLUE_ROOF_TILES("conquest:stone_full_20:13", "conquest:stone_corner_86:0", "conquest:stone_corner_88:0", "conquest:stone_verticalslab_98:3", "conquest:stone_verticalslab_100:3", "minecraft:stained_hardened_clay:3"),
    BLUE_SANDSTONE_BASE_COLUMN("conquest:stone_full_7:9", "conquest:stone_corner_10:0", "conquest:stone_verticalslab_10:0"),
    PINK_WOOL("minecraft:wool:6"),
    PLANNING_SIGN_COMMENT("conquest:stone_full_20:2"),
    WHITE_PLASTER("conquest:stone_full_10:14", "conquest:stone_fullpartial_6:2", "conquest:stone_corner_62:0", "conquest:stone_verticalslab_69:0"),
    PLASTER_WITH_MASONRY_LINES("conquest:stone_full_26:15"),
    YELLOW_TUDOR_V_FRAME("conquest:stone_full_23:5", "conquest:stone_corner_73:0", "conquest:stone_verticalslab_85:3"),
    JUKEBOX("minecraft:jukebox:0"),
    PILE_OF_SKELETONS("conquest:stone_full_13:12", "conquest:stone_corner_51:2", "conquest:stone_verticalslab_57:2"),
    GRAY_IVORY_PILLAR("conquest:stone_corner_65:2", "conquest:stone_verticalslab_78:1"),
    YELLOW_STAINED_GLASS("minecraft:stained_glass:4", "minecraft:stained_glass_pane:4"),
    MARBLE_BASE_COLUMN("conquest:stone_full_7:15", "conquest:stone_corner_12:0", "conquest:stone_verticalslab_12:0"),
    DECORATIVE_DARK_STONE("conquest:stone_full_19:11"),
    PURPLE("conquest:stone_corner_37:0", "conquest:stone_verticalslab_37:0"),
    PLANNING_SIGN_MIDDLECLASS("conquest:stone_full_20:0"),
    RED_BRICK_X_FRAME("conquest:stone_full_5:5", "conquest:stone_corner_32:3", "conquest:stone_verticalslab_32:3"),
    MOSSY_BLUE_SCHIST("conquest:stone_verticalslab_73:3"),
    WHITE_STUCCO_WALL("conquest:stone_fullpartial_3:3", "conquest:stone_corner_36:0", "conquest:stone_verticalslab_36:0"),
    BRICK_BOX_FRAME_VERTICAL_CONNECTION("conquest:stone_corner_29:3", "conquest:stone_verticalslab_29:3"),
    DOLOMITE("conquest:stone_verticalslab_55:0", "minecraft:stone:5"),
    PLANNING_SIGN_UPDATE("conquest:stone_full_20:10"),
    BLUE_WALL("conquest:stone_corner_41:3", "conquest:stone_verticalslab_41:3"),
    BRICK_BOX_FRAME_VERTICAL_CONNECTIONGRAY_TUDOR_X_FRAME("conquest:stone_full_4:11"),
    RED_STAINED_GLASS("minecraft:stained_glass:14", "minecraft:stained_glass_pane:14"),
    PINK_CONCRETE("minecraft:concrete:6"),
    LIGHT_BLUE_STAINED_GLASS("minecraft:stained_glass:3", "minecraft:stained_glass_pane:3"),
    ORANGE_WOOL("minecraft:wool:1"),
    GOLD_SANDSTONE_CAPITAL_COLUMN("conquest:stone_full_7:12", "conquest:stone_corner_11:0", "conquest:stone_verticalslab_11:0"),
    LAPIS_LAZULI_BLOCK("minecraft:lapis_block:0"),
    ENGRAVED_C("conquest:stone_full_8:13"),
    RED_BRICK_V_FRAME("conquest:stone_full_5:9", "conquest:stone_corner_33:1", "conquest:stone_verticalslab_33:1"),
    PLASTERED_STONE("conquest:stone_full_1:0", "conquest:stone_fullpartial_1:0", "conquest:stone_corner_1:0", "conquest:stone_verticalslab_1:0", "conquest:stone_arrowslit_1:0"),
    RED_BRICK_UP_ARROW_FRAME("conquest:stone_full_5:8", "conquest:stone_corner_33:0", "conquest:stone_verticalslab_33:0"),
    CLEAN_LIGHT_GRAY_STUCCO("conquest:stone_full_11:0", "conquest:stone_fullpartial_6:3", "conquest:stone_corner_62:2", "conquest:stone_verticalslab_69:2"),
    DARK_IRON("conquest:stone_corner_6:2", "conquest:stone_verticalslab_6:2", "conquest:stone_arrowslit_4:2"),
    DARK_RED_BRICK_BACK_SLASH_FRAME_VERTICAL_CONNECTION("conquest:stone_full_5:3", "conquest:stone_corner_31:3", "conquest:stone_verticalslab_31:3"),
    WHITE_WALL_DESIGN("conquest:stone_full_11:6", "conquest:stone_full_11:7", "conquest:stone_full_11:8", "conquest:stone_full_11:9", "conquest:stone_full_11:10", "conquest:stone_full_11:11", "conquest:stone_corner_18:3", "conquest:stone_corner_19:0", "conquest:stone_corner_19:1", "conquest:stone_corner_19:2", "conquest:stone_corner_19:3", "conquest:stone_corner_20:0", "conquest:stone_verticalslab_18:3", "conquest:stone_verticalslab_19:0", "conquest:stone_verticalslab_19:1", "conquest:stone_verticalslab_19:2", "conquest:stone_verticalslab_19:3", "conquest:stone_verticalslab_20:0"),
    RETICULATED_BRICKS("conquest:stone_full_16:6", "conquest:stone_corner_56:3", "conquest:stone_verticalslab_62:3"),
    BLUE_TUDOR_FORWARD_SLASH_FRAME("conquest:stone_full_21:9", "conquest:stone_corner_66:0", "conquest:stone_verticalslab_78:3"),
    BLUE_CONCRETE_POWDER("minecraft:concrete_powder:11"),
    ENGRAVED_K("conquest:stone_full_9:5"),
    COBBLESTONE_WITH_BRICK("conquest:stone_full_1:12"),
    CLAY_TILE("conquest:stone_corner_22:1", "conquest:stone_verticalslab_22:1"),
    ELVEN_WAVE_PILLAR("conquest:stone_corner_73:2", "conquest:stone_verticalslab_86:1"),
    OAK_WOOD_PLANKS("minecraft:planks:0"),
    BROWN_WOOD_SHINGLES("conquest:stone_full_20:11", "conquest:stone_corner_87:2", "conquest:stone_verticalslab_100:1"),
    COLORFUL_SLATE("conquest:stone_full_1:5", "conquest:stone_fullpartial_1:6", "conquest:stone_corner_2:1", "conquest:stone_verticalslab_2:1", "conquest:stone_arrowslit_1:3"),
    BIG_BLACK_INSCRIBED_SLAB_NO_SIDE_CTM("conquest:stone_full_10:9"),
    LIGHT_GRAY_STONEBRICK("conquest:stone_full_23:12", "conquest:stone_fullpartial_6:14", "conquest:stone_corner_74:3", "conquest:stone_verticalslab_87:2"),
    OXIDIZE_COPPER("conquest:stone_corner_84:1"),
    SANDSTONE_BRICK("conquest:stone_full_6:15", "conquest:stone_fullpartial_2:8", "conquest:stone_corner_22:0", "conquest:stone_verticalslab_22:0", "conquest:stone_arrowslit_7:1"),
    RED_BRICK_FORWARD_SLASH_FRAME("conquest:stone_full_5:6", "conquest:stone_corner_32:1", "conquest:stone_verticalslab_32:1"),
    HEWN_STONE("conquest:stone_full_1:2", "conquest:stone_fullpartial_1:5", "conquest:stone_fullpartial_6:9", "conquest:stone_corner_2:0", "conquest:stone_verticalslab_2:0", "conquest:stone_arrowslit_1:2"),
    NETHER_BRICK_PILLAR("conquest:stone_corner_5:3", "conquest:stone_verticalslab_5:3"),
    MOSSY_BRICK("conquest:stone_full_5:15", "conquest:stone_fullpartial_2:13", "conquest:stone_corner_34:2", "conquest:stone_verticalslab_34:2", "conquest:stone_arrowslit_8:2"),
    MOSSY_RED_BRICK("conquest:stone_full_6:3", "conquest:stone_fullpartial_3:1", "conquest:stone_corner_35:2", "conquest:stone_verticalslab_35:2", "conquest:stone_arrowslit_9:2"),
    YELLOW_TUDOR_BACK_SLASH_FRAME("conquest:stone_full_23:4", "conquest:stone_corner_72:3", "conquest:stone_verticalslab_85:2"),
    ROUGH_NATURAL_SANDSTONE("conquest:stone_verticalslab_66:1"),
    RED_SANDSTONE_BASE_COLUMN("conquest:stone_full_7:5", "conquest:stone_corner_8:3", "conquest:stone_verticalslab_8:3"),
    FISHSCALE_COBBLE("conquest:stone_full_1:10"),
    CYAN_CONCRETE("minecraft:concrete:9"),
    MAGENTA_WALL_DESIGN("conquest:stone_full_12:1", "conquest:stone_corner_37:1", "conquest:stone_verticalslab_37:1"),
    WHITE_CONCRETE("minecraft:concrete:0"),
    ACACIA_WOOD("minecraft:wooden_slab:4"),
    MAGENTA_WALL("conquest:stone_corner_37:2", "conquest:stone_verticalslab_37:2"),
    MARBLE_COLUMN_CAPITAL("conquest:stone_corner_14:3", "conquest:stone_verticalslab_14:3"),
    GOLD_BAR_PILE("conquest:stone_full_13:9", "conquest:stone_corner_43:1", "conquest:stone_verticalslab_43:1"),
    RED_CLAY("conquest:stone_full_19:8"),
    TUDOR_NARROW_FORWARD_SLASH_FRAME("conquest:stone_full_16:8", "conquest:stone_corner_57:1", "conquest:stone_verticalslab_63:1"),
    STONE_PILLAR("conquest:stone_corner_5:0", "conquest:stone_verticalslab_5:0"),
    NATURAL_ANDESITE("conquest:stone_corner_75:1", "conquest:stone_verticalslab_71:1"),
    AIR("minecraft:air:0");

    private static final Map<String, BlockIdentifier> idMappings = SeleneUtils.emptyConcurrentMap();
    private String[] ids;

    static {
        for (BlockIdentifier blockIdentifier : values()) {
            if (null == blockIdentifier.ids) continue;

            for (String id : blockIdentifier.ids) {
                idMappings.put(id, blockIdentifier);
            }
        }
    }

    BlockIdentifier(String... ids) {
        this.ids = ids;
    }

    public String[] getIds() {
        return this.ids;
    }

    public boolean isAir() {
        return BlockIdentifier.AIR == this;
    }

    public static BlockIdentifier ofItem(Item item) {
        return ofName(item.getDisplayName(Language.EN_US).toStringValue());
    }

    /**
     * Returns the BlockIdentifier of a specific blocks id.
     *
     * @param id The id of the block in a the format: 'minecraft:stone:1'
     * @return The {@link BlockIdentifier} of the id.
     */
    public static BlockIdentifier ofID(String id) {
        return idMappings.getOrDefault(id, BlockIdentifier.AIR);
//        return ofItem(getItemFromID(id));
    }

    public static BlockIdentifier ofName(String name) {
        return Exceptional.of(() -> valueOf(
                formatBlockName(
                    VariantIdentifier.getBlockNameWithoutVariant(name))
        )).orElse(BlockIdentifier.AIR);
    }

    /*
     * Note: VariantIdentifier.prepareForMatcher doesn't remove Vertical Connection as its convered to uppercase and
     * has underscores instead of spaces, so it doesn't match.
     */
    public static String formatBlockName(String name) {
        return VariantIdentifier.prepareForMatcher(
                name.trim()
                .toUpperCase()
                .replace(" ", "_")
                .replace("'", "_"));
    }
}
