name: 'Bug report'
description: 'If you found a bug, please report it here.'
labels: ['type: bug']
body:
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Provide a clear and concise description of the bug you encountered.'
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: 'Steps to Reproduce'
      description: 'List the steps that can be followed to reproduce the bug. Include as much detail as necessary.'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 'Expected Behavior'
      description: 'Describe what you expected to happen when following the steps above.'
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: 'Actual Behavior'
      description: 'Explain what actually happened when you followed the steps above.'
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 'Error messages or stack traces'
      description: 'If applicable, include any error messages or stack traces here.'
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: 'Additional context'
      description: 'Add any other context about the problem here.'
    validations:
      required: false
  - type: input
    id: related
    attributes:
      label: 'Related issues'
      description: 'If applicable, list any related issues here.'
    validations:
      required: false
  - type: textarea
    id: solutions
    attributes:
      label: 'Possible solutions'
      description: 'If you have any ideas on how to solve this bug, list them here.'
    validations:
      required: false
