name: 'Documentation'
description: 'Any issues related to documentation, such as missing or incorrect information.'
labels: ['type: documentation']
body:
  - type: dropdown
    id: type
    attributes:
      label: 'Type'
      description: 'What type of documentation issue is this?'
      options:
        - 'Missing information'
        - 'Incorrect information'
        - 'Other'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: 'Provide a clear and concise description of the documentation issue.'
    validations:
      required: true
  - type: input
    id: related
    attributes:
      label: 'Related issues'
      description: 'If applicable, list any related issues here.'
    validations:
      required: false
