name: 'Enhancement (of existing feature)'
description: 'Propose an enhancement to an existing feature.'
labels: [ 'type: enhancement' ]
body:
  - type: textarea
    id: description
    attributes:
      label: 'Description'
      description: "Provide a clear and concise description of the enhancement you'd like to propose."
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: 'Use case'
      description: 'Explain the use case or scenario where this enhancement would be valuable or necessary.'
    validations:
      required: true
  - type: input
    id: related
    attributes:
      label: 'Related issues'
      description: 'If applicable, list any related issues here.'
    validations:
      required: false
