name: 'Feature request'
description: 'If you want to add a feature to the project, please create an issue here.'
labels: ['type: feature request']
body:
  - type: textarea
    id: problem
    attributes:
      label: 'Related problem'
      description: 'Is your feature related to a problem? If so, please describe the problem.'
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: 'Requested feature'
      description: 'Describe the feature you want to add. Be as detailed as possible.'
    validations:
      required: true
