package org.dockbox.hartshorn.blockregistry.init;

import org.dockbox.hartshorn.blockregistry.init.VanillaProps.ModGroups;
import org.dockbox.hartshorn.blockregistry.init.VanillaProps.TypeList;

public class BeamsInit {

    public static void init() {
        TypeList types = null, typesVanilla = null;
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("oak_wood_beam")
                .texture("end", "minecraft:block/stripped_oak_log_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/oak/oak_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/oak/oak_wood_beam_wall_top")
                .texture("*", "minecraft:block/stripped_oak_log")
                //.parent(Blocks.STRIPPED_OAK_LOG.defaultBlockState())
                .register(typesVanilla);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("spruce_wood_beam")
                .texture("end", "minecraft:block/stripped_spruce_log_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/spruce/spruce_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/spruce/spruce_wood_beam_wall_top")
                .texture("*", "minecraft:block/stripped_spruce_log")
                //.parent(Blocks.STRIPPED_SPRUCE_LOG.defaultBlockState())
                .register(typesVanilla);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("birch_wood_beam")
                .texture("end", "minecraft:block/stripped_birch_log_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/birch/birch_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/birch/birch_wood_beam_wall_top")
                .texture("*", "minecraft:block/stripped_birch_log")
                //.parent(Blocks.STRIPPED_BIRCH_LOG.defaultBlockState())
                .register(typesVanilla);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("palm_wood_beam")
                .texture("end", "minecraft:block/stripped_jungle_log_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/palm_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/palm_wood_beam_wall_top")
                .texture("*", "minecraft:block/stripped_jungle_log")
                //.parent(Blocks.STRIPPED_JUNGLE_LOG.defaultBlockState())
                .register(typesVanilla);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("dark_oak_wood_beam")
                .texture("end", "minecraft:block/stripped_dark_oak_log_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/dark_oak_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/dark_oak_wood_beam_wall_top")
                .texture("*", "minecraft:block/stripped_dark_oak_log")
                .register(typesVanilla);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("acacia_wood_beam")
                .texture("end", "minecraft:block/stripped_acacia_log_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/acacia_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/acacia_wood_beam_wall_top")
                .texture("*", "minecraft:block/stripped_acacia_log")
                //.parent(Blocks.STRIPPED_ACACIA_LOG.defaultBlockState())
                .register(typesVanilla);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("apple_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/apple_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/apple_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/apple_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/apple_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("ash_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/ash_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/ash_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/ash_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/ash_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("aspen_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/aspen_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/aspen_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/aspen_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/aspen_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("beech_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/beech_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/beech_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/beech_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/beech_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("horse_chestnut_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/horse_chestnut_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/horse_chestnut_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/horse_chestnut_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/horse_chestnut_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("larch_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/larch_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/larch_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/larch_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/larch_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("mallorn_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/mallorn_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/mallorn_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/mallorn_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/mallorn_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("norway_spruce_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/norway_spruce_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/norway_spruce_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/norway_spruce_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/norway_spruce_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("pine_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/pine_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/pine_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/pine_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/pine_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("rowan_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/rowan_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/rowan_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/rowan_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/rowan_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("willow_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/willow_wood_beam_top")
                .texture("sidewall", "block/1_basic_refined/3_wood/willow_wood_beam_wall")
                .texture("topwall", "block/1_basic_refined/3_wood/willow_wood_beam_wall_top")
                .texture("*", "block/1_basic_refined/3_wood/willow_wood_beam")
                .register(types);

        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("wooden_beam")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("cross_beams")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("diagonal_beam_1")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("diagonal_beam_2")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("diagonal_beam_3")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("cross_beams_side")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("diagonal_beam_side_1")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("diagonal_beam_side_2")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("diagonal_beam_side_3")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("wooden_beam_vertical_centered")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .family("wooden_beam_vertical")
                .name("wooden_beam_horizontal_centered")
                .manual()
                .solid(false)
                .register(TypeList.of(Void.class));
        VanillaProps.planks()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .name("wooden_fancy_corbel")
                .manual()
                .solid(false)
                .blocking(false)
                .register(TypeList.of(Void.class));
        VanillaProps.planks()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .name("white_painted_corbel")
                .manual()
                .solid(false)
                .blocking(false)
                .register(TypeList.of(Void.class));
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("tarred_birch_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/tarred_birch_wood_beam_top")
                .texture("*", "block/1_basic_refined/3_wood/tarred_birch_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("tarred_dark_oak_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/tarred_dark_oak_wood_beam_top")
                .texture("*", "block/1_basic_refined/3_wood/tarred_dark_oak_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("tarred_oak_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/tarred_oak_wood_beam_top")
                .texture("*", "block/1_basic_refined/3_wood/tarred_oak_wood_beam")
                .register(types);
        VanillaProps.logs()
                .group(ModGroups.PLANKS_AND_BEAMS)
                .name("tarred_spruce_wood_beam")
                .texture("end", "block/1_basic_refined/3_wood/tarred_spruce_wood_beam_top")
                .texture("*", "block/1_basic_refined/3_wood/tarred_spruce_wood_beam")
                .register(types);
    }
}
