package org.dockbox.hartshorn.blockregistry.init;

import org.dockbox.hartshorn.blockregistry.init.VanillaProps.ModGroups;
import org.dockbox.hartshorn.blockregistry.init.VanillaProps.TypeList;

public class ColumnsInit {

    public static void init() {
        TypeList types = null;
        TypeList types1 = null;
        TypeList types2 = null;
        TypeList types3 = null;
        TypeList typesVanilla = null;
        TypeList typesLogParent = null;
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("fancy_stone_column")
                .texture("top", "minecraft:chiseled_stone_bricks_top")
                .texture("bottom", "minecraft:chiseled_stone_bricks_top")
                .texture("*", "minecraft:chiseled_stone_bricks")
                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("spiral_stone_column")
                .texture("top", "block/2_advanced_refined/1_stone/spiral_stone_column_top")
                .texture("bottom", "block/2_advanced_refined/1_stone/spiral_stone_column_top")
                .texture("*", "block/2_advanced_refined/1_stone/spiral_stone_column")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("simple_elven_column")
                .texture("top", "block/2_advanced_refined/1_stone/simple_elven_column")
                .texture("bottom", "block/2_advanced_refined/1_stone/simple_elven_column")
                .texture("*", "block/2_advanced_refined/1_stone/simple_elven_column")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.ADVANCED_CARPENTRY)
                .name("carved_ash_wood_pillar")
                .texture("top", "block/1_basic_refined/3_wood/ash_wood_planks")
                .texture("bottom", "block/1_basic_refined/3_wood/ash_wood_planks")
                .texture("*", "block/2_advanced_refined/7_wood/carved_ash_wood_pillar")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("simple_elven_column_design")
                .texture("end", "block/2_advanced_refined/1_stone/simple_elven_column_design_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/simple_elven_column_design_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/simple_elven_column_design_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/simple_elven_column_design")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("fancy_elven_pillar_design")
                .texture("top", "block/2_advanced_refined/1_stone/fancy_elven_column_design_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/fancy_elven_column_design_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/fancy_elven_pillar_design")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("fancy_elven_column_design")
                .texture("top", "block/2_advanced_refined/1_stone/fancy_elven_column_design_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/fancy_elven_column_design_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/fancy_elven_column_design")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("fancy_elven_marble_column")
                .texture("top", "block/2_advanced_refined/1_stone/3_marble/fancy_elven_marble_column_top")
                .texture("bottom", "block/2_advanced_refined/1_stone/3_marble/fancy_elven_marble_column_top")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/fancy_elven_marble_column")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("gothic_sandstone_column")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/gothic_sandstone_floor_tiles")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/gothic_sandstone_floor_tiles")
                .texture("*","block/2_advanced_refined/1_stone/5_sandstone/gothic_sandstone_column")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("fancy_dark_stone_column")
                .texture("top", "block/2_advanced_refined/1_stone/fancy_dark_stone_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/fancy_dark_stone_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/fancy_dark_stone_column")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("blue_schist_dwarven_column")
                .texture("top", "block/8_topography/1_stone/blue_schist")
                .texture("bottom", "block/8_topography/1_stone/blue_schist")
                .texture("*", "block/2_advanced_refined/1_stone/6_schist/blue_schist_dwarven_column")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("fancy_blue_schist_dwarven_column")
                .texture("top", "block/8_topography/1_stone/blue_schist")
                .texture("bottom", "block/8_topography/1_stone/blue_schist")
                .texture("*", "block/2_advanced_refined/1_stone/6_schist/fancy_blue_schist_dwarven_column")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.METAL)
                .name("carbonite_pillar")
                .texture("top", "minecraft:purpur_pillar_top")
                .texture("bottom", "minecraft:purpur_pillar_top")
                .texture("*", "minecraft:purpur_pillar")
                                .register(typesVanilla);
        VanillaProps.metal()
                .group(ModGroups.METAL)
                .name("old_rusted_metal_column")
                .texture("top", "block/2_advanced_refined/2_metal/old_rusted_large_metal_brick")
                .texture("bottom", "block/2_advanced_refined/2_metal/old_rusted_large_metal_brick")
                .texture("*", "block/2_advanced_refined/2_metal/old_rusted_metal_column")
                .register(types);
        VanillaProps.metal()
                .group(ModGroups.METAL)
                .name("old_rusted_metal_pillar")
                .texture("top", "block/2_advanced_refined/2_metal/old_rusted_large_metal_brick")
                .texture("bottom", "block/2_advanced_refined/2_metal/old_rusted_large_metal_brick")
                .texture("*", "block/2_advanced_refined/2_metal/old_rusted_metal_pillar")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("engraved_red_sandstone_pillar")
                .texture("top", "minecraft:block/red_sandstone_top")
                .texture("bottom", "minecraft:block/red_sandstone_top")
                .texture("*", "minecraft:block/chiseled_red_sandstone")
                                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("red_sandstone_pillar")
                .texture("top", "minecraft:block/red_sandstone_top")
                .texture("bottom", "minecraft:block/red_sandstone_top")
                .texture("*", "minecraft:block/cut_red_sandstone")
                                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("smooth_sandstone_column")
                .texture("top", "minecraft:block/sandstone_top")
                .texture("bottom", "minecraft:block/sandstone_bottom")
                .texture("*", "minecraft:block/cut_sandstone")
                                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("sandstone_column")
                .texture("end", "block/2_advanced_refined/1_stone/5_sandstone/sandstone_column_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/sandstone_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/sandstone_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/5_sandstone/sandstone_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("sandstone_column_with_sandstone_doric_capital")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/complex_sandstone_design")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/sandstone_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/5_sandstone/sandstone_column_with_sandstone_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("sandstone_column_with_sandstone_base")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/sandstone_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/complex_sandstone_design")
                .texture("*", "block/2_advanced_refined/1_stone/5_sandstone/sandstone_column_with_sandstone_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("red_column")
                .texture("end", "block/2_advanced_refined/1_stone/4_painted/red_column_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/red_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/red_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/red_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("red_column_with_marble_doric_capital")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/red_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/red_column_with_marble_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("red_column_with_marble_base")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/red_column_topbottom")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/red_column_with_marble_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("red_column_with_sandstone_doric_capital")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/complex_sandstone_design")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/red_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/red_column_with_sandstone_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("red_column_with_sandstone_base")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/red_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/complex_sandstone_design")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/red_column_with_sandstone_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("blue_column")
                .texture("end", "block/2_advanced_refined/1_stone/4_painted/blue_column_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/blue_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/blue_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/blue_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("blue_column_with_marble_doric_capital")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/blue_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/blue_column_with_marble_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("blue_column_with_marble_base")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/blue_column_topbottom")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/blue_column_with_marble_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("blue_column_with_sandstone_doric_capital")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/complex_sandstone_design")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/blue_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/blue_column_with_sandstone_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("blue_column_with_sandstone_base")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/blue_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/complex_sandstone_design")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/blue_column_with_sandstone_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("gold_column")
                .texture("end", "block/2_advanced_refined/1_stone/4_painted/gold_column_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/gold_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/gold_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/gold_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("gold_column_with_marble_doric_capital")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/gold_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/gold_column_with_marble_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("gold_column_with_marble_base")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/gold_column_topbottom")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/gold_column_with_marble_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("gold_column_with_sandstone_doric_capital")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/complex_sandstone_design")
                .texture("bottom", "block/2_advanced_refined/1_stone/4_painted/gold_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/gold_column_with_sandstone_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("gold_column_with_sandstone_base")
                .texture("top", "block/2_advanced_refined/1_stone/4_painted/gold_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/complex_sandstone_design")
                .texture("*", "block/2_advanced_refined/1_stone/4_painted/gold_column_with_sandstone_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("marble_column")
                .texture("end", "block/2_advanced_refined/1_stone/3_marble/marble_column_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/3_marble/marble_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/3_marble/marble_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/marble_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("marble_column_with_marble_doric_capital")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("bottom", "block/2_advanced_refined/1_stone/3_marble/marble_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/marble_column_with_marble_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("marble_column_with_marble_base")
                .texture("top", "block/2_advanced_refined/1_stone/3_marble/marble_column_topbottom")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/marble_column_with_marble_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("marble_ionian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("sandstone_ionian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("marble_corinthian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("sandstone_corinthian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("polychrome_corinthian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("elven_marble_base")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/elven_marble_base")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("elven_marble_capital")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/elven_marble_capital")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("smooth_marble_column")
                .texture("block/2_advanced_refined/1_stone/3_marble/smooth_marble_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("smooth_marble_column_with_marble_base")
                .texture("top", "block/2_advanced_refined/1_stone/3_marble/smooth_marble_column")
                .texture("bottom", "minecraft:block/quartz_block_bottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/smooth_marble_column_with_marble_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("smooth_marble_column_with_marble_doric_capital")
                .texture("top", "minecraft:block/quartz_block_top")
                .texture("bottom", "block/2_advanced_refined/1_stone/3_marble/smooth_marble_column")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/smooth_marble_column_with_marble_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("polished_parian_marble_column")
                .texture("top", "minecraft:block/quartz_pillar_top")
                .texture("bottom", "minecraft:block/quartz_pillar_top")
                .texture("*", "minecraft:block/quartz_pillar")
                                .register(typesVanilla);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("polished_parian_marble_column_base")
                .texture("top", "minecraft:block/quartz_pillar_top")
                .texture("bottom", "minecraft:block/quartz_pillar_top")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/quartz_column_base")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("polished_parian_marble_column_capital")
                .texture("top", "minecraft:block/quartz_pillar_top")
                .texture("bottom", "minecraft:block/quartz_pillar_top")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/quartz_column_capital")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("yellow_travertine_decor_pillar")
                .manual()
                .register(typesLogParent);
        
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("dark_sandstone_column")
                .texture("end", "block/2_advanced_refined/1_stone/5_sandstone/dark_sandstone_column_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/dark_sandstone_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/dark_sandstone_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/5_sandstone/dark_sandstone_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("dark_sandstone_column_with_dark_sandstone_doric_capital")
                .texture("top", "block/1_basic_refined/1_stone/5_sandstone/brown_sandstone_brick")
                .texture("bottom", "block/2_advanced_refined/1_stone/5_sandstone/dark_sandstone_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/5_sandstone/dark_sandstone_column_with_dark_sandstone_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("dark_sandstone_column_with_dark_sandstone_base")
                .texture("top", "block/2_advanced_refined/1_stone/5_sandstone/dark_sandstone_column_topbottom")
                .texture("bottom", "block/1_basic_refined/1_stone/5_sandstone/brown_sandstone_brick")
                .texture("*", "block/2_advanced_refined/1_stone/5_sandstone/dark_sandstone_column_with_dark_sandstone_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("dark_sandstone_ionian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("dark_sandstone_corinthian_capital")
                .manual()
                .register(TypeList.of(Void.class));

        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("limestone_column")
                .texture("end", "block/2_advanced_refined/1_stone/2_limestone/limestone_column_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/2_limestone/limestone_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/2_limestone/limestone_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/2_limestone/limestone_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("limestone_column_with_limestone_doric_capital")
                .texture("top", "minecraft:block/stone")
                .texture("bottom", "block/2_advanced_refined/1_stone/2_limestone/limestone_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/2_limestone/limestone_column_with_limestone_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("limestone_column_with_limestone_base")
                .texture("top", "block/2_advanced_refined/1_stone/2_limestone/limestone_column_topbottom")
                .texture("bottom", "minecraft:block/stone")
                .texture("*", "block/2_advanced_refined/1_stone/2_limestone/limestone_column_with_limestone_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("limestone_ionian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("limestone_corinthian_capital")
                .manual()
                .register(TypeList.of(Void.class));

        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("travertine_column")
                .texture("end", "block/2_advanced_refined/1_stone/3_marble/travertine_column_topbottom")
                .texture("top", "block/2_advanced_refined/1_stone/3_marble/travertine_column_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/3_marble/travertine_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/travertine_column")
                .register(typesLogParent);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("travertine_column_with_travertine_doric_capital")
                .texture("top", "block/1_basic_refined/1_stone/4_marble/travertine_slab_topbottom")
                .texture("bottom", "block/2_advanced_refined/1_stone/3_marble/travertine_column_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/travertine_column_with_travertine_doric_capital")
                .register(types1);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("travertine_column_with_travertine_base")
                .texture("top", "block/2_advanced_refined/1_stone/3_marble/travertine_column_topbottom")
                .texture("bottom", "block/1_basic_refined/1_stone/4_marble/travertine_slab_topbottom")
                .texture("*", "block/2_advanced_refined/1_stone/3_marble/travertine_column_with_travertine_base")
                .register(types2);
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("travertine_ionian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.stone()
                .group(ModGroups.COLUMNS)
                .name("travertine_corinthian_capital")
                .manual()
                .register(TypeList.of(Void.class));
        
    }
}
