package org.dockbox.hartshorn.blockregistry.init;

import org.dockbox.hartshorn.blockregistry.init.VanillaProps.ModGroups;
import org.dockbox.hartshorn.blockregistry.init.VanillaProps.TypeList;

public class SandGravelInit {

    public static void init() {
        TypeList types = null, typesVanilla = null, typesOverlay = null;
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("white_concrete_powder")
                .texture("minecraft:block/white_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("orange_concrete_powder")
                .texture("minecraft:block/orange_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("magenta_concrete_powder")
                .texture("minecraft:block/magenta_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("light_blue_concrete_powder")
                .texture("minecraft:block/light_blue_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("yellow_concrete_powder")
                .texture("minecraft:block/yellow_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("lime_concrete_powder")
                .texture("minecraft:block/lime_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("pink_concrete_powder")
                .texture("minecraft:block/pink_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("gray_concrete_powder")
                .texture("minecraft:block/gray_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("light_gray_concrete_powder")
                .texture("minecraft:block/light_gray_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("cyan_concrete_powder")
                .texture("minecraft:block/cyan_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("purple_concrete_powder")
                .texture("minecraft:block/purple_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("blue_concrete_powder")
                .texture("minecraft:block/blue_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("brown_concrete_powder")
                .texture("minecraft:block/brown_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("green_concrete_powder")
                .texture("minecraft:block/green_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("red_concrete_powder")
                .texture("minecraft:block/red_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.PLASTER_STUCCO_AND_PAINT)
                .name("black_concrete_powder")
                .texture("minecraft:block/black_concrete_powder")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("sand")
                .texture("minecraft:block/sand")
                                .register(typesVanilla);
        VanillaProps.grassySand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("grass_and_sand")
                .texture("overlay", "block/8_topography/4_grass_leaves/grass_overlay")
                .texture("*", "block/8_topography/3_sand_clay/grass_and_sand")
                                .grassColor()
                .register(typesOverlay);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("sand_and_gravel")
                .texture("block/8_topography/3_sand_clay/sand_and_gravel")
                .register(types);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("sand_and_vegetation")
                .texture("block/8_topography/3_sand_clay/sand_and_vegetation")
                .register(types);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("wet_sand")
                .texture("block/8_topography/3_sand_clay/wet_sand")
                .register(types);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("wet_sand_and_gravel")
                .texture("block/8_topography/3_sand_clay/wet_sand_and_gravel")
                .register(types);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("wet_sand_and_vegetation")
                .texture("block/8_topography/3_sand_clay/wet_sand_and_vegetation")
                .register(types);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("red_sand")
                .texture("minecraft:block/red_sand")
                                .register(typesVanilla);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("red_sand_and_gravel")
                .texture("block/8_topography/3_sand_clay/red_sand_and_gravel")
                .register(types);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("red_sand_and_vegetation")
                .texture("block/8_topography/3_sand_clay/red_sand_and_vegetation")
                .register(types);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("sandstone_debris")
                .texture("block/8_topography/6_debris_gravel/sandstone_debris")
                .register(types);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("schist_debris")
                .texture("block/8_topography/6_debris_gravel/schist_debris")
                .register(types);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("mossy_sandstone_debris")
                .texture("block/8_topography/6_debris_gravel/mossy_sandstone_debris")
                .register(types);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("mossy_schist_debris")
                .texture("block/8_topography/6_debris_gravel/mossy_schist_debris")
                .register(types);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("gravel")
                .texture("minecraft:block/gravel")
                                .register(typesVanilla);
        VanillaProps.grassyGravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("grassy_gravel")
                .texture("overlay", "block/8_topography/4_grass_leaves/grass_overlay")
                .texture("*", "block/8_topography/6_debris_gravel/grassy_gravel")
                                .grassColor()
                .register(typesOverlay);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("small_stones")
                .texture("block/8_topography/6_debris_gravel/small_stones")
                .register(types);
        VanillaProps.grassyStone()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("grassy_small_stones")
                .texture("overlay", "block/8_topography/4_grass_leaves/grass_overlay")
                .texture("*", "block/8_topography/6_debris_gravel/grassy_small_stones")
                .grassColor()
                                .register(typesOverlay);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("brown_gravel")
                .texture("block/8_topography/6_debris_gravel/brown_gravel")
                .register(types);
        VanillaProps.earth()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("zen_garden_dirt")
                .texture("block/8_topography/6_debris_gravel/zen_garden_dirt")
                .register(types);
        VanillaProps.gravel()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("smooth_pebbles")
                .texture("block/8_topography/6_debris_gravel/smooth_pebbles")
                .register(types);
        VanillaProps.stone()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("netherrack")
                .texture("minecraft:block/netherrack")
                                .register(typesVanilla);
        VanillaProps.earth()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("soul_sand")
                .texture("minecraft:block/soul_sand")
                                .register(typesVanilla);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("ash")
                .texture("block/8_topography/6_debris_gravel/ash")
                .register(types);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("dry_river_sand")
                .texture("block/8_topography/3_sand_clay/dry_river_sand")
                .register(types);
        VanillaProps.sand()
                .group(ModGroups.SAND_AND_GRAVEL)
                .name("wet_river_sand")
                .texture("block/8_topography/3_sand_clay/wet_river_sand")
                .register(types);
    }
}
