package org.dockbox.hartshorn.blockregistry.init;

import org.dockbox.hartshorn.blockregistry.init.VanillaProps.ModGroups;
import org.dockbox.hartshorn.blockregistry.init.VanillaProps.TypeList;

public class SaplingsInit {

    public static void init() {
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("alder_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("apple_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("aspen_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("cherry_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("downy_willow_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("gorse_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("grape_vine_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("horse_chestnut_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("larch_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("mallorn_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("orange_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("pear_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("pine_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("plum_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("rowan_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
        VanillaProps.grass()
                .group(ModGroups.LEAVES)
                .name("willow_tree_sapling")
                .manual()
                .register(TypeList.of(Void.class));
    }
}
