<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.dockbox.hartshorn</groupId>
  <artifactId>hartshorn-platform-build</artifactId>
  <packaging>pom</packaging>
  <version>${revision}</version>

  <name>Hartshorn Platform Build</name>
  <description>Build configuration for Hartshorn Maven modules</description>

  <url>https://hartshorn.dockbox.org/</url>
  <inceptionYear>2019</inceptionYear>
  <organization>
    <name>Dockbox OSS</name>
    <url>https://dockbox.org/</url>
  </organization>

  <licenses>
    <license>
      <name>Apache License, Version 2.0</name>
      <url>https://www.apache.org/licenses/LICENSE-2.0</url>
      <distribution>repo</distribution>
    </license>
  </licenses>

  <scm>
    <url>https://github.com/Dockbox-OSS/Hartshorn</url>
    <connection>scm:git:git://github.com/Dockbox-OSS/Hartshorn</connection>
    <developerConnection>scm:git:git://github.com/Dockbox-OSS/Hartshorn</developerConnection>
  </scm>

  <developers>
    <developer>
      <name>Guus Lieben</name>
      <email>guuslieben@dockbox.org</email>
      <url>https://github.com/GuusLieben</url>
      <organization>Dockbox OSS</organization>
      <organizationUrl>https://dockbox.org/</organizationUrl>
    </developer>
  </developers>

  <issueManagement>
    <system>GitHub</system>
    <url>https://www.github.com/Dockbox-OSS/Hartshorn/issues</url>
  </issueManagement>

  <properties>
    <!-- Project version, keep in sync with root pom.xml -->
    <revision>0.7.0</revision>
    <hartshorn.version>${revision}</hartshorn.version>

    <!-- Project properties, inherited by all submodules -->
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.build.outputTimestamp>2026-01-01T00:00:00Z</project.build.outputTimestamp>
    <java.version>25</java.version>

    <!-- Language versions, also inherited by BOM -->
    <groovy.version>5.0.3</groovy.version>
    <kotlin.version>2.4.20</kotlin.version>
    <scala.version>3.3.7</scala.version>

    <!-- Maven plugin versions, in alphabetical order -->
    <plugin.buildhelper.version>3.6.2</plugin.buildhelper.version>
    <plugin.compiler.version>3.16.0</plugin.compiler.version>
    <plugin.deploy.version>3.2.0</plugin.deploy.version>
    <plugin.flatten.version>1.8.0</plugin.flatten.version>
    <plugin.gmaven.version>5.1.0</plugin.gmaven.version>
    <plugin.gpg.version>3.2.8</plugin.gpg.version>
    <plugin.jar.version>3.5.1</plugin.jar.version>
    <plugin.javadoc.version>3.12.0</plugin.javadoc.version>
    <plugin.kotlin.version>${kotlin.version}</plugin.kotlin.version>
    <plugin.scala.version>4.10.0</plugin.scala.version>
    <plugin.source.version>3.4.0</plugin.source.version>
    <plugin.staging.version>1.7.0</plugin.staging.version>
    <plugin.openrewrite.version>6.46.1</plugin.openrewrite.version>
    <plugin.versions.version>2.22.0</plugin.versions.version>
  </properties>

  <profiles>
    <profile>
      <id>staging</id>
      <activation>
        <property>
          <name>staging</name>
          <value>true</value>
        </property>
      </activation>

      <distributionManagement>
        <repository>
          <id>ossrh</id>
          <name>OSSRH Staging</name>
          <url>https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/</url>
          <layout>default</layout>
          <uniqueVersion>false</uniqueVersion>
        </repository>
        <snapshotRepository>
          <id>ossrh</id>
          <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
        </snapshotRepository>
      </distributionManagement>

      <build>
        <plugins>

          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-gpg-plugin</artifactId>
            <executions>
              <execution>
                <id>sign-artifacts</id>
                <phase>verify</phase>
                <goals>
                  <goal>sign</goal>
                </goals>
                <configuration>
                  <gpgArguments>
                    <arg>--pinentry-mode</arg>
                    <arg>loopback</arg>
                  </gpgArguments>
                </configuration>
              </execution>
            </executions>
          </plugin>
          <!-- Deployment configuration -->
          <plugin>
            <groupId>org.sonatype.central</groupId>
            <artifactId>central-publishing-maven-plugin</artifactId>
            <version>0.9.0</version>
            <extensions>true</extensions>
            <configuration>
              <publishingServerId>central</publishingServerId>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

  <build>
    <testResources>
      <testResource>
        <directory>src/test/resources</directory>
      </testResource>
      <testResource>
        <directory>src/testFixtures/resources</directory>
      </testResource>
    </testResources>
    <pluginManagement>
      <!-- Plugin management, in alphabetical order of version property -->
      <plugins>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>build-helper-maven-plugin</artifactId>
          <version>${plugin.buildhelper.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>${plugin.compiler.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>flatten-maven-plugin</artifactId>
          <version>${plugin.flatten.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.gmavenplus</groupId>
          <artifactId>gmavenplus-plugin</artifactId>
          <version>${plugin.gmaven.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>${plugin.jar.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>${plugin.javadoc.version}</version>
        </plugin>
        <plugin>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-maven-plugin</artifactId>
          <version>${plugin.kotlin.version}</version>
        </plugin>
        <plugin>
          <groupId>net.alchim31.maven</groupId>
          <artifactId>scala-maven-plugin</artifactId>
          <version>${plugin.scala.version}</version>
        </plugin>
        <plugin>
          <groupId>org.openrewrite.maven</groupId>
          <artifactId>rewrite-maven-plugin</artifactId>
          <version>${plugin.openrewrite.version}</version>
        </plugin>
        <plugin>
          <groupId>org.codehaus.mojo</groupId>
          <artifactId>versions-maven-plugin</artifactId>
          <version>${plugin.versions.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>${plugin.deploy.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>${plugin.gpg.version}</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>${plugin.source.version}</version>
        </plugin>
        <plugin>
          <groupId>org.sonatype.plugins</groupId>
          <artifactId>nexus-staging-maven-plugin</artifactId>
          <version>${plugin.staging.version}</version>
        </plugin>
      </plugins>
    </pluginManagement>

    <plugins>
      <!-- Standard build configurations -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <configuration>
          <updatePomFile>true</updatePomFile>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <execution>
            <id>flatten.clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>test-jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- Testing -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>add-gradle-testfixtures</id>
            <phase>generate-test-sources</phase>
            <goals>
              <goal>add-test-source</goal>
            </goals>
            <configuration>
              <sources>
                <source>src/testFixtures/java</source>
              </sources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Language support -->
      <plugin>
        <groupId>org.codehaus.gmavenplus</groupId>
        <artifactId>gmavenplus-plugin</artifactId>
        <configuration>
          <targetBytecode>25</targetBytecode>
        </configuration>
        <executions>
          <execution>
            <id>compile</id>
            <goals>
              <goal>compile</goal>
            </goals>
          </execution>
          <execution>
            <id>test-compile</id>
            <goals>
              <goal>compileTests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>net.alchim31.maven</groupId>
        <artifactId>scala-maven-plugin</artifactId>
        <configuration>
          <scalaVersion>${scala.version}</scalaVersion>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.jetbrains.kotlin</groupId>
        <artifactId>kotlin-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>compile</id>
            <phase>compile</phase>
            <goals>
              <goal>compile</goal>
            </goals>
            <configuration>
              <sourceDirs>
                <sourceDir>${project.basedir}/src/main/java</sourceDir>
                <sourceDir>${project.basedir}/src/main/kotlin</sourceDir>
                <sourceDir>${project.basedir}/src/main/scala</sourceDir>
              </sourceDirs>
            </configuration>
          </execution>
          <execution>
            <id>test-compile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>test-compile</goal>
            </goals>
            <configuration>
              <sourceDirs>
                <sourceDir>${project.basedir}/src/test/java</sourceDir>
                <sourceDir>${project.basedir}/src/test/kotlin</sourceDir>
                <sourceDir>${project.basedir}/src/test/scala</sourceDir>
              </sourceDirs>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.openrewrite.maven</groupId>
        <artifactId>rewrite-maven-plugin</artifactId>
        <version>6.23.0</version>
        <configuration>
          <exportDatatables>true</exportDatatables>
          <activeRecipes>
            <recipe>org.openrewrite.java.testing.assertj.Assertj</recipe>
            <recipe>org.openrewrite.java.jspecify.JSpecifyBestPractices</recipe>
          </activeRecipes>
        </configuration>
        <dependencies>
          <dependency>
            <groupId>org.openrewrite.recipe</groupId>
            <artifactId>rewrite-testing-frameworks</artifactId>
            <version>3.21.3</version>
          </dependency>
        </dependencies>
      </plugin>

      <!-- Distribution staging -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-sources</id>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>${plugin.javadoc.version}</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- Dependency version upgrades -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>versions-maven-plugin</artifactId>
        <configuration>
          <ignoredVersions>
            <ignoredVersion>.*-[Aa][Ll][Pp][Hh][Aa].*</ignoredVersion>
            <ignoredVersion>.*-[Bb][Ee][Tt][Aa].*</ignoredVersion>
            <ignoredVersion>.*-[Rr][Cc].*</ignoredVersion>
            <ignoredVersion>.*-[Mm][Rr]?.*</ignoredVersion>
            <ignoredVersion>.*-[Ee][Aa].*</ignoredVersion>
          </ignoredVersions>
          <generateBackupPoms>false</generateBackupPoms>

          <!--
          Exclude Kotlin plugin version from being updated, as this should always reference the kotlin.version property
          instead of being directly updated by the versions plugin.
          -->
          <excludeProperties>plugin.kotlin.version,plugin.errorprone.version</excludeProperties>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <reporting>
    <excludeDefaults>true</excludeDefaults>
  </reporting>
</project>
