/*
 * Copyright 2019-2025 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.dockbox.hartshorn.hsl.customizer;

import org.dockbox.hartshorn.hsl.ast.statement.Statement;
import org.dockbox.hartshorn.hsl.interpreter.Interpreter;
import org.dockbox.hartshorn.hsl.interpreter.ResultCollector;
import org.dockbox.hartshorn.hsl.lexer.Comment;
import org.dockbox.hartshorn.hsl.lexer.Lexer;
import org.dockbox.hartshorn.hsl.parser.TokenParser;
import org.dockbox.hartshorn.hsl.runtime.ScriptRuntime;
import org.dockbox.hartshorn.hsl.semantic.Resolver;
import org.dockbox.hartshorn.hsl.token.DefaultTokenRegistry;
import org.dockbox.hartshorn.hsl.token.Token;
import org.dockbox.hartshorn.hsl.token.TokenRegistry;
import org.dockbox.hartshorn.launchpad.context.DefaultApplicationAwareContext;
import org.dockbox.hartshorn.util.option.Option;

import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * The standard context which tracks the state of the execution of a script. It is used by the
 * {@link org.dockbox.hartshorn.hsl.runtime.StandardRuntime} to track the state of the script's
 * execution, and store its various executors. Everything but the original script can be
 * customized during the script's execution, though some runtimes may not support this.
 *
 * @since 0.4.12
 *
 * @author Guus Lieben
 */
public class ScriptContext extends DefaultApplicationAwareContext implements ResultCollector {

    private static final String GLOBAL_RESULT = ScriptContext.createSafeRuntimeVariable("result");
    protected Map<String, Object> results = new ConcurrentHashMap<>();

    private final ScriptRuntime runtime;
    private final String source;

    private String scriptName = "HSL Script %d".formatted(this.hashCode());

    private TokenRegistry tokenRegistry = DefaultTokenRegistry.createDefault();
    private List<Token> tokens = List.of();
    private List<Statement> statements = List.of();
    private List<Comment> comments = List.of();

    private Lexer lexer;
    private TokenParser parser;
    private Resolver resolver;
    private Interpreter interpreter;

    public ScriptContext(ScriptRuntime runtime, String source) {
        super(runtime.applicationContext());
        this.source = source;
        this.runtime = runtime;
    }

    /**
     * The original source code of the script. This source code is not modified
     * during the execution of the script, and can be used for error reporting
     * and debugging purposes.
     *
     * @return The original source code of the script.
     */
    public String source() {
        return this.source;
    }

    /**
     * The name of the script. This name is used for error reporting and
     * debugging purposes. By default, this name is "HSL Script &lt;hashcode&gt;",
     * but it can be customized using {@link #scriptName(String)}.
     *
     * @return The name of the script.
     */
    public String scriptName() {
        return this.scriptName;
    }

    /**
     * Sets the name of the script.
     *
     * @param scriptName The name of the script.
     * @return The current context.
     */
    public ScriptContext scriptName(String scriptName) {
        this.scriptName = scriptName;
        return this;
    }

    /**
     * The list of tokens generated by the lexer, or an empty list if the
     * lexer has not yet been run.
     *
     * @return The list of tokens.
     */
    public List<Token> tokens() {
        return this.tokens;
    }

    /**
     * Sets the list of tokens generated by the lexer. This should typically only be set
     * by either the lexer itself or the owning runtime, but is exposed for customization
     * through {@link CodeCustomizer customizers}.
     *
     * @param tokens The list of tokens.
     * @return The current context.
     */
    public ScriptContext tokens(List<Token> tokens) {
        this.tokens = tokens;
        return this;
    }

    /**
     * The token registry used by the lexer and parser to identify tokens. By default,
     * this is a {@link DefaultTokenRegistry}.
     *
     * @return The token registry.
     */
    public TokenRegistry tokenRegistry() {
        return this.tokenRegistry;
    }

    /**
     * Sets the token registry used by the lexer and parser to identify tokens.
     *
     * @param tokenRegistry The token registry.
     * @return The current context.
     */
    public ScriptContext tokenRegistry(TokenRegistry tokenRegistry) {
        this.tokenRegistry = tokenRegistry;
        return this;
    }

    /**
     * The list of statements generated by the parser, or an empty list if the parser
     * has not yet been run.
     *
     * @return The list of statements.
     */
    public List<Statement> statements() {
        return this.statements;
    }

    /**
     * Sets the list of statements generated by the parser. This should typically only be set
     * by either the parser itself or the owning runtime, but is exposed for customization
     * through {@link CodeCustomizer customizers}.
     *
     * @param statements The list of statements.
     * @return The current context.
     */
    public ScriptContext statements(List<Statement> statements) {
        this.statements = statements;
        return this;
    }

    /**
     * The list of comments found in the script, or an empty list if no comments
     * were found.
     *
     * @return The list of comments.
     */
    public List<Comment> comments() {
        return this.comments;
    }

    /**
     * Sets the list of comments found in the script. This should typically only be set
     * by the lexer itself or the owning runtime, but is exposed for customization
     * through {@link CodeCustomizer customizers}.
     *
     * @param comments The list of comments found in the script.
     * @return The current context.
     */
    public ScriptContext comments(List<Comment> comments) {
        this.comments = comments;
        return this;
    }

    /**
     * The lexer used to tokenize the script source code. This lexer is responsible
     * for breaking the source code into tokens, which are then parsed into statements.
     *
     * @see Lexer
     * @see org.dockbox.hartshorn.hsl.lexer.SimpleTokenRegistryLexer
     *
     * @return The lexer used for tokenization.
     */
    public Lexer lexer() {
        return this.lexer;
    }

    /**
     * Sets the lexer used to tokenize the script source code.
     *
     * @param lexer The lexer to use for tokenization.
     * @return The current context.
     */
    public ScriptContext lexer(Lexer lexer) {
        this.lexer = lexer;
        return this;
    }

    /**
     * The parser used to parse the tokens into statements. This parser is responsible
     * for interpreting the tokens and creating an abstract syntax tree (AST).
     *
     * @see TokenParser
     * @see org.dockbox.hartshorn.hsl.parser.StandardTokenParser
     *
     * @return The parser used for parsing tokens.
     */
    public TokenParser parser() {
        return this.parser;
    }

    /**
     * Sets the parser used to parse the tokens into statements. This parser is responsible
     * for interpreting the tokens and creating an abstract syntax tree (AST).
     *
     * @param parser The parser to use for parsing tokens.
     * @return The current context.
     */
    public ScriptContext parser(TokenParser parser) {
        this.parser = parser;
        return this;
    }

    /**
     * The resolver used to resolve identifiers in the script. This resolver is responsible for
     * semantic analysis, ensuring that variables and functions are correctly defined and used.
     *
     * @see Resolver
     *
     * @return The resolver used for resolving identifiers.
     */
    public Resolver resolver() {
        return this.resolver;
    }

    /**
     * Sets the resolver used to resolve identifiers in the script. This resolver is responsible for
     * semantic analysis, ensuring that variables and functions are correctly defined and used.
     *
     * @param resolver The resolver to use for resolving identifiers.
     * @return The current context.
     */
    public ScriptContext resolver(Resolver resolver) {
        this.resolver = resolver;
        return this;
    }

    /**
     * The interpreter used to execute the script. This interpreter is responsible for
     * executing the statements in the abstract syntax tree (AST) and producing results.
     *
     * @see Interpreter
     * @see org.dockbox.hartshorn.hsl.interpreter.SimpleVisitorInterpreter
     *
     * @return The interpreter used for script execution.
     */
    public Interpreter interpreter() {
        return this.interpreter;
    }

    /**
     * Sets the interpreter used to execute the script. This interpreter is responsible for
     * executing the statements in the abstract syntax tree (AST) and producing results.
     *
     * @param interpreter The interpreter to use for script execution.
     * @return The current context.
     */
    public ScriptContext interpreter(Interpreter interpreter) {
        this.interpreter = interpreter;
        return this;
    }

    /**
     * The runtime that is executing the script. This runtime provides the environment
     * in which the script is executed, including configuration options, external modules,
     * and global variables.
     *
     * @return The script runtime.
     */
    public ScriptRuntime runtime() {
        return this.runtime;
    }

    @Override
    public void addResult(Object value) {
        this.addResult(GLOBAL_RESULT, value);
    }

    @Override
    public void addResult(String id, Object value) {
        this.results.put(id, value);
    }

    @Override
    public <T> Option<T> result(Class<T> type) {
        return this.result(GLOBAL_RESULT, type);
    }

    @Override
    public Option<?> result() {
        return this.result(GLOBAL_RESULT);
    }

    @Override
    public <T> Option<T> result(String id, Class<T> type) {
        return Option.of(this.results.get(id)).ofType(type);
    }

    @Override
    public Option<?> result(String id) {
        return Option.of(this.results.get(id));
    }

    @Override
    public void clear() {
        this.results.clear();
    }

    /**
     * Creates a safe runtime variable name which is unlikely to collide with user-defined
     * variables.
     *
     * @param name The base name of the variable.
     * @return A safe runtime variable name.
     */
    public static String createSafeRuntimeVariable(String name) {
        return "$__%s__$".formatted(name);
    }
}
