hartshorn:
  web:
    port: 8081
    jetty:
      threadpool: org.eclipse.jetty.util.thread.VirtualThreadPool
      scheduler: org.eclipse.jetty.util.thread.ScheduledExecutorScheduler
      bufferpool: org.eclipse.jetty.io.ArrayByteBufferPool$Quadratic
    logging:
      enabled: true
