#
# Template Antora playbook configuration for local (branch) builds.
#
site:
  title: Hartshorn Framework
  start_page: launchpad::index.adoc

urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: latest

ui:
  bundle:
    url: https://github.com/Dockbox-OSS/Antora-Dockbox-UI/releases/download/latest/ui-bundle.zip
    snapshot: true

content:
  sources:
    # Working in ./hartshorn-assembly/antora, but Git repository is in ./ (root). Note that this
    # has to be prefixed with ./, as ../ directly is interpreted from root directory.
    - url: ./../..
      # Local build, use whatever is in HEAD
      branches: HEAD
      # Effectively null, no versioning on non-released documentation
      version: ~
      edit_url: https://github.com/Dockbox-OSS/Hartshorn/tree/HEAD/{path}
      start_paths:
        - hartshorn-inject/src/main/docs
        - hartshorn-inject-configurations/src/main/docs
        - hartshorn-launchpad/src/main/docs
        - hartshorn-testsuite/src/main/docs
        - hartshorn-util/src/main/docs
        - hartshorn-spi/src/main/docs
        - hartshorn-proxy/src/main/docs
        - hartshorn-proxy-javassist/src/main/docs
        - hartshorn-introspect/src/main/docs
        - hartshorn-introspect-reflection/src/main/docs
        - hartshorn-reporting/src/main/docs
        - hartshorn-hsl/src/main/docs
