<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.dockbox.hartshorn</groupId>
  <artifactId>hartshorn-launchpad-starter</artifactId>
  <version>${revision}</version>
  <packaging>pom</packaging>

  <name>Hartshorn Launchpad Starter</name>
  <description>Launchpad configuration for Maven artifacts</description>

  <properties>
    <revision>0.7.0</revision>
    <java.version>25</java.version>
    <hartshorn.version>${project.version}</hartshorn.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.build.outputTimestamp>2026-01-01T00:00:00Z</project.build.outputTimestamp>

    <!-- Maven plugin versions, in alphabetical order -->
    <plugin.compiler.version>3.11.0</plugin.compiler.version>
    <plugin.flatten.version>1.7.0</plugin.flatten.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.dockbox.hartshorn</groupId>
        <artifactId>hartshorn-bom</artifactId>
        <version>${hartshorn.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <dependencies>
    <dependency>
      <groupId>org.dockbox.hartshorn</groupId>
      <artifactId>hartshorn-launchpad</artifactId>
    </dependency>
    <dependency>
      <groupId>org.dockbox.hartshorn</groupId>
      <artifactId>hartshorn-support</artifactId>
    </dependency>

    <!-- Default core Hartshorn implementations -->
    <dependency>
      <groupId>org.dockbox.hartshorn</groupId>
      <artifactId>hartshorn-proxy-javassist</artifactId>
    </dependency>
    <dependency>
      <groupId>org.dockbox.hartshorn</groupId>
      <artifactId>hartshorn-introspect-reflection</artifactId>
    </dependency>

    <!-- Default logging implementation -->
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <optional>true</optional>
    </dependency>

    <!-- Default supported property formats -->
    <dependency>
      <groupId>tools.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-properties</artifactId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <groupId>tools.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-yaml</artifactId>
      <optional>true</optional>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>${plugin.flatten.version}</version>
        <configuration>
          <updatePomFile>true</updatePomFile>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <execution>
            <id>flatten.clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${plugin.compiler.version}</version>
        <configuration>
          <release>${java.version}</release>
          <fork>false</fork>
          <encoding>UTF-8</encoding>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
