name: Build all

on: pull_request

jobs:
  buildSource:
    needs: [license]
    name: Build all (source JDK)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up source JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: "Build (source JDK)"
        run: mvn clean install -DskipTests -Pci,all
  buildTarget:
    needs: [buildSource]
    strategy:
      fail-fast: false
      matrix:
        java: [18, 19]
    name: Build all (target JDK ${{ matrix.java }})
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: "Build (Java ${{ matrix.java }})"
        run: mvn clean install -DskipTests -Pci,all