# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SELENE_AT }}
          submodules: recursive
      - name: Grant execute permission for gradlew (NMS)
        working-directory: selene-nms-1.12
        run: chmod +x gradlew
      - name: Build NMS (Gradle Wrapper)
        working-directory: selene-nms-1.12
        run: ./gradlew build -x test
      - name: Build (Gradle)
        run: gradle build -x test
