name: OWASP Dependency Check

on: pull_request

jobs:
  depCheck:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Prepare for dependency check
        run: mvn clean install -DskipTests -P ci,all
      - name: Analyze dependencies
        run: mvn dependency-check:check -Dowasp.skip=false -P ci,all
      - name: Archive dependency reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: dependency-check-report
          path: /hartshorn-*/target/dependency-check-report.html