name: Hartshorn

on: pull_request

jobs:
  license:
    name: License check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Check license headers
        run: ./gradlew checkLicenses
  build:
    needs: [license]
    strategy:
      fail-fast: false
      matrix:
        java: [17, 18, 19]
    name: Build all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: "Build (Java ${{ matrix.java }})"
        run: ./gradlew build -x test
  test:
    needs: [license, build]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]
        java: [17, 18, 19]
    name: Unit tests
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: "Unit testing (OS: ${{ matrix.os }}, Java: ${{ matrix.java }})"
        run: ./gradlew test
  coverage:
    needs: [test]
    strategy:
      fail-fast: false
      matrix:
        module: [
          "cache",
          "commands",
          "config",
          "core",
          "data",
          "events",
          "hsl",
          "i18n",
          "jpa",
          "reporting",
          "test-suite",
          "web",
        ]
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run tests
        run: ./gradlew :hartshorn-${{ matrix.module }}:test
      - name: Create and verify coverage report
        run: ./gradlew :hartshorn-${{ matrix.module }}:jacocoTestCoverageVerification
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.3
        with:
          title: "Code coverage: ${{ matrix.module }}"
          update-comment: true
          paths: ${{ github.workspace }}/hartshorn-${{ matrix.module }}/build/reports/jacoco/testCoverage/testCoverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

