# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Verify JavaDocs

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Checkout submodules
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.SELENE_AT }}
          submodules: recursive
      - name: Build with Maven
        run: mvn -B javadoc:aggregate --file pom.xml
