name: License header check

on: pull_request

jobs:
  depCheck:
    name: License header check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Check license headers
        run: mvn license:check -Pci,all
