name: Hartshorn Core

on:
  pull_request:
    paths:
      - 'hartshorn-core/**'

jobs:
  build:
    name: Build (JDK 17)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew hartshorn-core:build -x test -x copyArtifacts
  compatBuild:
    needs: [ build ]
    name: Compatibility Build (JDK 17, ${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew hartshorn-core:build -x test -x copyArtifacts
  test:
    needs: [ build ]
    strategy:
      fail-fast: false
      matrix:
        java: [ 17, 18, 19 ]
    name: Unit tests (JDK ${{ matrix.java }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up source JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test
        run: ./gradlew hartshorn-core:test
