name: Hartshorn OWASP Dependency Check

on: pull_request

jobs:
  depCheck:
    name: Gradle dependency check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Analyze dependencies
        run: ./gradlew dependencyCheckAnalyze
