name: Build documentation

on: workflow_call

jobs:
  buildDocs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up source JDK
        uses: actions/setup-java@v3
        with:
          java-version: 25
          distribution: temurin
      - name: Build developer documentation
        run: mvn clean install -DskipTests -P ci -DincludeModules=false -Dantora.skip=false -Dantora.playbook=playbook-local.yml
      - name: Archive Antora artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Antora documentation archive
          path: target/site
          if-no-files-found: error
          retention-days: 7
      - name: Build Javadocs
        run: mvn clean install site -DskipTests -P ci -Djavadoc.skip=false
      - name: Archive Javadoc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Javadoc archive
          path: target/reports/apidocs
          if-no-files-found: error
          retention-days: 7