name: Build documentation

on: workflow_call

jobs:
  buildDocs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build developer documentation
        run: "npm --prefix hartshorn-assembly/antora run antora -- playbook-local.yml"
        shell: bash
      - name: Archive Antora artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Antora documentation archive
          path: hartshorn-assembly/antora/target/site
          if-no-files-found: error
          retention-days: 7
      - name: Set up source JDK
        uses: actions/setup-java@v3
        with:
          java-version: 25
          distribution: temurin
      - name: Build Javadocs
        run: mvn clean install site -DskipTests -P ci -Djavadoc.skip=false
      - name: Archive Javadoc artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Javadoc archive
          path: target/reports/apidocs
          if-no-files-found: error
          retention-days: 7