name: Build documentation

on: workflow_call

jobs:
  buildDocs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up source JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
      - name: Build developer documentation
        run: mvn clean antora:antora -P ci -Dantora.skip=false -Dantora.playbook=playbook-local.yml
      - name: Build Javadocs
        run: mvn javadoc:aggregate -P ci -Djavadoc.skip=false
      - name: Archive documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation archive
          path: target/site
          if-no-files-found: error
          retention-days: 7