name: Hartshorn

on: pull_request

jobs:
  testSource:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    name: Unit tests (source JDK)
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - name: Set up source JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: "Unit testing (OS: ${{ matrix.os }}, source JDK)"
        run: mvn clean test -Pci,all
  testTarget:
    needs: [testSource]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [18, 19]
    name: Unit tests (target JDK ${{ matrix.java }})
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: "Unit testing (OS: ${{ matrix.os }}, Java: ${{ matrix.java }})"
        run: mvn clean test -Pci,all
  coverage:
    needs: [testSource]
    name: Code coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up source JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Run tests
        run: mvn clean verify -Djacoco.skip=false -Dcoverage.skip=false -Pci,all
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: ${{ github.workspace }}/hartshorn-assembly/target/site/jacoco-aggregate/