name: Pull Request
on: [pull_request]

jobs:
  prebuild_check_codestyle:
    name: Pre-build checks
    uses: ./.github/workflows/prebuild/check.codestyle.yml
  prebuild_check_license:
    name: Pre-build checks
    uses: ./.github/workflows/prebuild/check.license.yml
  prebuild_check_dependency:
    name: Pre-build checks
    uses: ./.github/workflows/prebuild/check.dependency.yml
  build:
    name: Build modules
    needs:
      - prebuild_check_codestyle
      - prebuild_check_license
      - prebuild_check_dependency
    uses: ./.github/workflows/build/build.modules.yml
  postbuild_test:
    name: Post-build actions
    needs:
      - build
    uses: ./.github/workflows/postbuild/test.coverage.yml
  postbuild_documentation:
    name: Post-build actions
    needs:
      - postbuild_test
    uses: ./.github/workflows/postbuild/build.docs.yml